[package]
name = "trellis-runtime-acceptance"
version = "0.0.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
futures-util = "0.3"
runtime-trellis = { path = "crates/runtime-trellis" }
trellis-rs = "0.100.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
