// Generated by Trellis. Do not edit.
import { TrellisError } from "@oatscenter/trellis/generated";
import type { SerializableErrorData } from "@oatscenter/trellis/generated";
import * as Types1 from "../../types/_internal/p1.js";
export type NotFoundErrorData = SerializableErrorData & {
	readonly type: "trellis.health@v1::NotFoundError";
} & Types1.HealthNotFoundErrorData;
export declare class NotFoundError extends TrellisError<NotFoundErrorData> {
	static readonly type: "trellis.health@v1::NotFoundError";
	static readonly payloadCodec: typeof Types1.HealthNotFoundErrorDataCodec;
	readonly name: "NotFoundError";
	readonly data: NotFoundErrorData;
	constructor(data: NotFoundErrorData);
	static fromSerializable(data: unknown): NotFoundError;
	toSerializable(): NotFoundErrorData;
}
export type UnexpectedErrorData = SerializableErrorData & {
	readonly type: "trellis.health@v1::UnexpectedError";
};
export declare class UnexpectedError extends TrellisError<UnexpectedErrorData> {
	static readonly type: "trellis.health@v1::UnexpectedError";
	readonly name: "UnexpectedError";
	readonly data: UnexpectedErrorData;
	constructor(data: UnexpectedErrorData);
	static fromSerializable(data: unknown): UnexpectedError;
	toSerializable(): UnexpectedErrorData;
}
export type ValidationErrorData = SerializableErrorData & {
	readonly type: "trellis.health@v1::ValidationError";
};
export declare class ValidationError extends TrellisError<ValidationErrorData> {
	static readonly type: "trellis.health@v1::ValidationError";
	readonly name: "ValidationError";
	readonly data: ValidationErrorData;
	constructor(data: ValidationErrorData);
	static fromSerializable(data: unknown): ValidationError;
	toSerializable(): ValidationErrorData;
}
export type InspectInput = Types1.HealthInspectRequest;
export type InspectOutput = Types1.HealthInspectResponse;
export type MetricsInput = Types1.HealthMetricsRequest;
export type MetricsOutput = Types1.HealthMetricsResponse;
export type QueryInput = Types1.HealthQueryRequest;
export type QueryOutput = Types1.HealthQueryResponse;
export type SummaryInput = Types1.HealthSummaryRequest;
export type SummaryOutput = Types1.HealthSummaryResponse;
export type StatusChangedEvent = Types1.HealthStatusChangedEvent;
export type WatchInput = Types1.HealthWatchRequest;
export type WatchEvent = Types1.HealthWatchFrame;
declare const __api: {
	readonly identity: "trellis.health@v1";
	readonly actions: {
		readonly "rpc:Inspect": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Inspect";
			readonly input: typeof Types1.HealthInspectRequestCodec;
			readonly output: typeof Types1.HealthInspectResponseCodec;
			readonly errors: readonly [typeof NotFoundError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Metrics": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Metrics";
			readonly input: typeof Types1.HealthMetricsRequestCodec;
			readonly output: typeof Types1.HealthMetricsResponseCodec;
			readonly errors: readonly [typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Query": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Query";
			readonly input: typeof Types1.HealthQueryRequestCodec;
			readonly output: typeof Types1.HealthQueryResponseCodec;
			readonly errors: readonly [typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: "cursor";
		};
		readonly "rpc:Summary": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Summary";
			readonly input: typeof Types1.HealthSummaryRequestCodec;
			readonly output: typeof Types1.HealthSummaryResponseCodec;
			readonly errors: readonly [typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "event:StatusChanged": {
			readonly kind: "event";
			readonly descriptorName: "event:StatusChanged";
			readonly payload: typeof Types1.HealthStatusChangedEventCodec;
			readonly parameters: readonly [];
		};
		readonly "live:Watch": {
			readonly kind: "live";
			readonly descriptorName: "live:Watch";
			readonly input: typeof Types1.HealthWatchRequestCodec;
			readonly event: typeof Types1.HealthWatchFrameCodec;
		};
	};
	readonly packageEvidence: unknown;
};
export declare const API: typeof __api;
export declare const API_DIGEST: "6OM4Ykuq1pnElpYu8cbd4tHaom7W6U-PaZ29qX66L-w";
export {};
