// Generated by Trellis. Do not edit.
export type CreateOrderRequest = {
	readonly customerId: string;
	readonly [key: string]: unknown;
};
export declare const CreateOrderRequestCodec: {
	decode(value: unknown): CreateOrderRequest;
	encode(value: CreateOrderRequest): unknown;
};
export type CreateOrderResponse = {
	readonly customerId: string;
	readonly orderId: string;
	readonly [key: string]: unknown;
};
export declare const CreateOrderResponseCodec: {
	decode(value: unknown): CreateOrderResponse;
	encode(value: CreateOrderResponse): unknown;
};
