// Generated by Trellis. Do not edit.
import { TrellisError } from "@oatscenter/trellis/generated";
import type { SerializableErrorData } from "@oatscenter/trellis/generated";
import * as Types1 from "../../types/_internal/p1.js";
export type ConflictData = SerializableErrorData & {
	readonly type: "trellis.events@v1::Conflict";
} & Types1.EventsErrorData;
export declare class Conflict extends TrellisError<ConflictData> {
	static readonly type: "trellis.events@v1::Conflict";
	static readonly payloadCodec: typeof Types1.EventsErrorDataCodec;
	readonly name: "Conflict";
	readonly data: ConflictData;
	constructor(data: ConflictData);
	static fromSerializable(data: unknown): Conflict;
	toSerializable(): ConflictData;
}
export type ForbiddenData = SerializableErrorData & {
	readonly type: "trellis.events@v1::Forbidden";
} & Types1.EventsErrorData;
export declare class Forbidden extends TrellisError<ForbiddenData> {
	static readonly type: "trellis.events@v1::Forbidden";
	static readonly payloadCodec: typeof Types1.EventsErrorDataCodec;
	readonly name: "Forbidden";
	readonly data: ForbiddenData;
	constructor(data: ForbiddenData);
	static fromSerializable(data: unknown): Forbidden;
	toSerializable(): ForbiddenData;
}
export type NotFoundErrorData = SerializableErrorData & {
	readonly type: "trellis.events@v1::NotFoundError";
} & Types1.EventsNotFoundErrorData;
export declare class NotFoundError extends TrellisError<NotFoundErrorData> {
	static readonly type: "trellis.events@v1::NotFoundError";
	static readonly payloadCodec: typeof Types1.EventsNotFoundErrorDataCodec;
	readonly name: "NotFoundError";
	readonly data: NotFoundErrorData;
	constructor(data: NotFoundErrorData);
	static fromSerializable(data: unknown): NotFoundError;
	toSerializable(): NotFoundErrorData;
}
export type UnavailableData = SerializableErrorData & {
	readonly type: "trellis.events@v1::Unavailable";
} & Types1.EventsErrorData;
export declare class Unavailable extends TrellisError<UnavailableData> {
	static readonly type: "trellis.events@v1::Unavailable";
	static readonly payloadCodec: typeof Types1.EventsErrorDataCodec;
	readonly name: "Unavailable";
	readonly data: UnavailableData;
	constructor(data: UnavailableData);
	static fromSerializable(data: unknown): Unavailable;
	toSerializable(): UnavailableData;
}
export type UnexpectedErrorData = SerializableErrorData & {
	readonly type: "trellis.events@v1::UnexpectedError";
};
export declare class UnexpectedError extends TrellisError<UnexpectedErrorData> {
	static readonly type: "trellis.events@v1::UnexpectedError";
	readonly name: "UnexpectedError";
	readonly data: UnexpectedErrorData;
	constructor(data: UnexpectedErrorData);
	static fromSerializable(data: unknown): UnexpectedError;
	toSerializable(): UnexpectedErrorData;
}
export type UnreplayableOriginalData = SerializableErrorData & {
	readonly type: "trellis.events@v1::UnreplayableOriginal";
} & Types1.EventsErrorData;
export declare class UnreplayableOriginal extends TrellisError<UnreplayableOriginalData> {
	static readonly type: "trellis.events@v1::UnreplayableOriginal";
	static readonly payloadCodec: typeof Types1.EventsErrorDataCodec;
	readonly name: "UnreplayableOriginal";
	readonly data: UnreplayableOriginalData;
	constructor(data: UnreplayableOriginalData);
	static fromSerializable(data: unknown): UnreplayableOriginal;
	toSerializable(): UnreplayableOriginalData;
}
export type ValidationErrorData = SerializableErrorData & {
	readonly type: "trellis.events@v1::ValidationError";
};
export declare class ValidationError extends TrellisError<ValidationErrorData> {
	static readonly type: "trellis.events@v1::ValidationError";
	readonly name: "ValidationError";
	readonly data: ValidationErrorData;
	constructor(data: ValidationErrorData);
	static fromSerializable(data: unknown): ValidationError;
	toSerializable(): ValidationErrorData;
}
export type ConsumersInspectInput = Types1.EventsConsumersInspectRequest;
export type ConsumersInspectOutput = Types1.EventsConsumersInspectResponse;
export type ConsumersQueryInput = Types1.EventsConsumersQueryRequest;
export type ConsumersQueryOutput = Types1.EventsConsumersQueryResponse;
export type ConsumersReportDeliveryInput = Types1.EventsConsumersReportDeliveryRequest;
export type ConsumersReportDeliveryOutput = Types1.EventsConsumersReportDeliveryResponse;
export type DeadLettersDismissInput = Types1.EventsDeadLettersDismissRequest;
export type DeadLettersDismissOutput = Types1.EventsDeadLettersDismissResponse;
export type DeadLettersInspectInput = Types1.EventsDeadLettersInspectRequest;
export type DeadLettersInspectOutput = Types1.EventsDeadLettersInspectResponse;
export type DeadLettersQueryInput = Types1.EventsDeadLettersQueryRequest;
export type DeadLettersQueryOutput = Types1.EventsDeadLettersQueryResponse;
export type DeadLettersReplayInput = Types1.EventsDeadLettersReplayRequest;
export type DeadLettersReplayOutput = Types1.EventsDeadLettersReplayResponse;
export type DiagnosticsInput = Types1.EventsDiagnosticsRequest;
export type DiagnosticsOutput = Types1.EventsDiagnosticsResponse;
export type InspectInput = Types1.EventsInspectRequest;
export type InspectOutput = Types1.EventsInspectResponse;
export type MetricsInput = Types1.EventsMetricsRequest;
export type MetricsOutput = Types1.EventsMetricsResponse;
export type QueryInput = Types1.EventsQueryRequest;
export type QueryOutput = Types1.EventsQueryResponse;
export type WatchInput = Types1.EventsWatchRequest;
export type WatchEvent = Types1.EventsWatchFrame;
declare const __api: {
	readonly identity: "trellis.events@v1";
	readonly actions: {
		readonly "rpc:Consumers.Inspect": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Consumers.Inspect";
			readonly input: typeof Types1.EventsConsumersInspectRequestCodec;
			readonly output: typeof Types1.EventsConsumersInspectResponseCodec;
			readonly errors: readonly [typeof NotFoundError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Consumers.Query": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Consumers.Query";
			readonly input: typeof Types1.EventsConsumersQueryRequestCodec;
			readonly output: typeof Types1.EventsConsumersQueryResponseCodec;
			readonly errors: readonly [typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: "cursor";
		};
		readonly "rpc:Consumers.ReportDelivery": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Consumers.ReportDelivery";
			readonly input: typeof Types1.EventsConsumersReportDeliveryRequestCodec;
			readonly output: typeof Types1.EventsConsumersReportDeliveryResponseCodec;
			readonly errors: readonly [typeof Conflict, typeof Forbidden, typeof NotFoundError, typeof Unavailable, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:DeadLetters.Dismiss": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:DeadLetters.Dismiss";
			readonly input: typeof Types1.EventsDeadLettersDismissRequestCodec;
			readonly output: typeof Types1.EventsDeadLettersDismissResponseCodec;
			readonly errors: readonly [typeof Conflict, typeof Forbidden, typeof NotFoundError, typeof Unavailable, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:DeadLetters.Inspect": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:DeadLetters.Inspect";
			readonly input: typeof Types1.EventsDeadLettersInspectRequestCodec;
			readonly output: typeof Types1.EventsDeadLettersInspectResponseCodec;
			readonly errors: readonly [typeof Forbidden, typeof NotFoundError, typeof Unavailable, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:DeadLetters.Query": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:DeadLetters.Query";
			readonly input: typeof Types1.EventsDeadLettersQueryRequestCodec;
			readonly output: typeof Types1.EventsDeadLettersQueryResponseCodec;
			readonly errors: readonly [typeof Forbidden, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: "cursor";
		};
		readonly "rpc:DeadLetters.Replay": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:DeadLetters.Replay";
			readonly input: typeof Types1.EventsDeadLettersReplayRequestCodec;
			readonly output: typeof Types1.EventsDeadLettersReplayResponseCodec;
			readonly errors: readonly [typeof Conflict, typeof Forbidden, typeof NotFoundError, typeof Unavailable, typeof UnreplayableOriginal, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Diagnostics": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Diagnostics";
			readonly input: typeof Types1.EventsDiagnosticsRequestCodec;
			readonly output: typeof Types1.EventsDiagnosticsResponseCodec;
			readonly errors: readonly [typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Inspect": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Inspect";
			readonly input: typeof Types1.EventsInspectRequestCodec;
			readonly output: typeof Types1.EventsInspectResponseCodec;
			readonly errors: readonly [typeof NotFoundError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Metrics": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Metrics";
			readonly input: typeof Types1.EventsMetricsRequestCodec;
			readonly output: typeof Types1.EventsMetricsResponseCodec;
			readonly errors: readonly [typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Query": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Query";
			readonly input: typeof Types1.EventsQueryRequestCodec;
			readonly output: typeof Types1.EventsQueryResponseCodec;
			readonly errors: readonly [typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: "cursor";
		};
		readonly "feed:Watch": {
			readonly kind: "feed";
			readonly descriptorName: "feed:Watch";
			readonly input: typeof Types1.EventsWatchRequestCodec;
			readonly event: typeof Types1.EventsWatchFrameCodec;
		};
	};
	readonly packageEvidence: unknown;
};
export declare const API: typeof __api;
export declare const API_DIGEST: "ByInt82orMBbflrAMLFBGWM8wUI97_J8ci4ra39Sby0";
export {};
