<script lang="ts">
  import { browser } from "$app/environment";
  import { onMount } from "svelte";
  import PortalBrand from "$lib/components/PortalBrand.svelte";
  import { trellisUrl } from "$lib/portal_config";
  import {
    accountFlowIdFromUrl,
    flowKindLabel,
    loadAccountFlowState,
    type AccountFlowState,
  } from "./page_state";

  let flowId = $state<string | null>(null);
  let flowState = $state.raw<AccountFlowState | null>(null);
  let loading = $state(true);
  let error = $state<string | null>(null);

  const active = $derived(flowState?.status === "active" ? flowState : null);

  function currentFlowId(): string | null {
    if (!browser) return null;
    return accountFlowIdFromUrl(new URL(window.location.href));
  }

  async function loadFlow(): Promise<void> {
    flowId = currentFlowId();
    if (!flowId) {
      error = "Missing invitation flow id. Open the invitation link generated by Trellis.";
      loading = false;
      return;
    }
    loading = true;
    error = null;
    try {
      flowState = await loadAccountFlowState(trellisUrl, flowId);
    } catch (caught) {
      error = caught instanceof Error ? caught.message : String(caught);
    } finally {
      loading = false;
    }
  }

  onMount(() => {
    if (!browser) return;
    void loadFlow();
  });
</script>

<svelte:head>
  <title>Accept invitation · Trellis</title>
</svelte:head>

{#snippet targetSummary()}
  {#if active?.target}
    <section class="portal-subtle-panel rounded-box p-4 text-sm leading-6">
      <p class="portal-section-label">Target account</p>
      <p class="mt-1 font-semibold text-base-content">{active.target.name ?? active.target.email ?? active.target.userId}</p>
      {#if active.target.email && active.target.email !== active.target.name}
        <p class="portal-copy">{active.target.email}</p>
      {/if}
      <p class="mono mt-1 break-all text-xs text-base-content/65">{active.target.userId}</p>
    </section>
  {/if}
{/snippet}

<main class="portal-shell flex min-h-screen justify-center px-4 py-10 sm:px-6" data-theme="portal">
  <div class="portal-page w-full max-w-md">
    <header class="portal-header"><PortalBrand subtitle="Account invitation" /></header>
    <div class="portal-body">

      {#if loading}
        <div class="flex items-center gap-4 py-3" aria-live="polite">
          <span class="loading loading-ring loading-lg" aria-hidden="true"></span>
          <div><p class="text-sm font-medium text-base-content">Loading invitation</p><p class="portal-copy text-xs">Resolving account-flow state.</p></div>
        </div>
      {:else if flowState?.status === "expired"}
        <div><h1 class="text-xl font-semibold tracking-[-0.025em] text-base-content">Invitation expired</h1><p class="portal-copy mt-2 text-sm">This invitation is missing or no longer active. Ask an administrator for a new link.</p></div>
      {:else if flowState?.status === "consumed"}
        <div><h1 class="text-xl font-semibold tracking-[-0.025em] text-base-content">Invitation already used</h1><p class="portal-copy mt-2 text-sm">This {flowKindLabel(flowState.kind)} request has already been completed.</p></div>
      {:else if active}
        <div><h1 class="text-xl font-semibold tracking-[-0.025em] text-base-content">Invitation links are no longer supported</h1><p class="portal-copy mt-2 text-sm">This route no longer accepts account-flow links. Ask an administrator for a current account setup or reset link.</p></div>
        {@render targetSummary()}
        <div class="alert alert-warning text-sm" role="alert"><span>This link is for {flowKindLabel(active.kind)}, not an invitation, and cannot be completed from this page.</span></div>
      {/if}

      {#if error}<div class="alert alert-error text-sm" role="alert"><span>{error}</span></div>{/if}
    </div>
  </div>
</main>
