[package]
name = "trellis-test-generated"
version = "0.100.0-rc.2"

[sources]
admin = "contract.trellis"

[dependencies]
trellis = { package = "trellis", path = "../../../crates/runtime" }

[generate.typescript]
output = "trellis"
