// Generated by Trellis. Do not edit.
// @ts-self-types="./mod.d.ts"
import * as Api0 from "../../apis/upgrade/mod.js";
/** Developer selections and local State codecs; never principal installation evidence. */
export const request = {
	id: "client-upgrade-fixture.Caller",
	kind: "browser",
	requiredCapabilities: ["client-upgrade-fixture.upgrade@v1::echo"],
	optionalCapabilities: [],
	uses: [{
		api: Api0.API,
		actions: [{
			descriptorName: "rpc:Echo",
			direction: "call",
			optionalCapabilities: []
		}],
		optionalCapabilities: []
	}],
	states: {}
};
export default request;
