// Generated by Trellis. Do not edit.
import type { AppRequestDescriptor } from "@oatscenter/trellis/generated";
import * as Api0 from "../../apis/upgrade/mod.js";
/** Developer selections and local State codecs; never principal installation evidence. */
export declare const request: AppRequestDescriptor & {
	readonly id: "client-upgrade-fixture.Caller";
	readonly kind: "browser";
	readonly requiredCapabilities: readonly ["client-upgrade-fixture.upgrade@v1::echo"];
	readonly optionalCapabilities: readonly [];
	readonly uses: readonly [{
		readonly api: typeof Api0.API;
		readonly actions: readonly [{
			readonly descriptorName: "rpc:Echo";
			readonly direction: "call";
			readonly optionalCapabilities: readonly [];
		}];
		readonly optionalCapabilities: readonly [];
	}];
	readonly states: {};
};
export type Request = typeof request;
export default request;
