<script lang="ts">
  import { browser } from "$app/environment";
  import { onMount } from "svelte";
  import PortalBrand from "$lib/components/PortalBrand.svelte";
  import { trellisUrl } from "$lib/portal_config";
  import {
    accountFlowIdFromUrl,
    completeAccountFlowLocalPassword,
    defaultProfileValue,
    flowKindLabel,
    hasLocalProvider,
    isExpectedPasswordFlow,
    loadAccountFlowState,
    passwordMinimumLength,
    passwordPolicyError,
    passwordPolicyHint,
    passwordFlowAction,
    passwordFlowTitle,
    unavailableProviders,
    type AccountFlowState,
    type LocalPasswordSuccess,
  } from "./page_state";

  let flowId = $state<string | null>(null);
  let flowState = $state.raw<AccountFlowState | null>(null);
  let loading = $state(true);
  let submitting = $state(false);
  let error = $state<string | null>(null);
  let completion = $state<LocalPasswordSuccess | null>(null);
  let password = $state("");
  let confirmPassword = $state("");
  let name = $state("");
  let email = $state("");
  let defaultsApplied = false;

  const active = $derived(flowState?.status === "active" ? flowState : null);
  const isResetFlow = $derived(active?.kind === "password_reset");
  const supportsLocal = $derived(Boolean(active && (isResetFlow || hasLocalProvider(active))));
  const title = $derived(active ? passwordFlowTitle(active.kind) : "Set your password");
  const action = $derived(active ? passwordFlowAction(active.kind) : "Save password");
  const fixedUsername = $derived(active && !isResetFlow ? defaultProfileValue(active, "username").trim() : "");
  const passwordMinLength = $derived(active ? passwordMinimumLength(active) : null);
  const passwordCurrentError = $derived(active ? passwordPolicyError(active, password) : null);
  const passwordHelp = $derived(active ? passwordCurrentError ?? passwordPolicyHint(active) : "");
  const passwordsMatch = $derived(password.length > 0 && password === confirmPassword);
  const confirmError = $derived(confirmPassword.length > 0 && !passwordsMatch ? "Passwords do not match" : null);
  const canSubmit = $derived(Boolean(active && flowId && supportsLocal && (isResetFlow || fixedUsername) && password && passwordsMatch && !passwordCurrentError && !submitting && !completion));

  function currentFlowId(): string | null {
    if (!browser) return null;
    return accountFlowIdFromUrl(new URL(window.location.href));
  }

  function applyDefaults(): void {
    if (!active || defaultsApplied) return;
    name = defaultProfileValue(active, "name");
    email = defaultProfileValue(active, "email");
    defaultsApplied = true;
  }

  async function loadFlow(): Promise<void> {
    flowId = currentFlowId();
    if (!flowId) {
      error = "Missing password flow id. Open the password setup or reset link generated by Trellis.";
      loading = false;
      return;
    }
    loading = true;
    error = null;
    try {
      flowState = await loadAccountFlowState(trellisUrl, flowId);
      applyDefaults();
    } catch (caught) {
      error = caught instanceof Error ? caught.message : String(caught);
    } finally {
      loading = false;
    }
  }

  async function submitLocal(): Promise<void> {
    if (!flowId || !active) return;
    const policyError = passwordPolicyError(active, password);
    if (policyError) {
      error = policyError;
      return;
    }
    submitting = true;
    error = null;
    try {
      completion = await completeAccountFlowLocalPassword(
        trellisUrl,
        flowId,
        {
          username: isResetFlow ? "" : fixedUsername,
          password,
          name,
          email,
        },
      );
      password = "";
      confirmPassword = "";
    } catch (caught) {
      error = caught instanceof Error ? caught.message : String(caught);
    } finally {
      submitting = false;
    }
  }

  onMount(() => {
    if (!browser) return;
    void loadFlow();
  });
</script>

<svelte:head><title>Password · Trellis</title></svelte:head>

{#snippet targetSummary()}
  {#if active?.target}
    <section class="portal-subtle-panel rounded-box p-4 text-sm leading-6">
      <p class="portal-section-label">Target account</p>
      <p class="mt-1 font-semibold text-base-content">{active.target.name ?? active.target.email ?? active.target.userId}</p>
      {#if active.target.email && active.target.email !== active.target.name}<p class="portal-copy">{active.target.email}</p>{/if}
      <p class="mono mt-1 break-all text-xs text-base-content/65">{active.target.userId}</p>
    </section>
  {/if}
{/snippet}

<main class="portal-shell flex min-h-screen justify-center px-4 py-10 sm:px-6" data-theme="portal">
  <div class="portal-page w-full max-w-md">
    <header class="portal-header"><PortalBrand subtitle="Password" /></header>
    <div class="portal-body">
      {#if loading}
        <div class="flex items-center gap-4 py-3" aria-live="polite"><span class="loading loading-ring loading-lg" aria-hidden="true"></span><div><p class="text-sm font-medium text-base-content">Loading password request</p><p class="portal-copy text-xs">Resolving account-flow state.</p></div></div>
      {:else if completion}
        <div><h1 class="text-xl font-semibold tracking-[-0.025em] text-base-content">Password saved</h1><p class="portal-copy mt-2 text-sm">Your local credentials were updated successfully.</p></div>
        <div class="portal-subtle-panel rounded-box p-4 text-sm leading-6 text-base-content/70"><p class="portal-section-label">Canonical user</p><p class="mono mt-1 break-all text-base-content">{completion.userId}</p></div>
      {:else if flowState?.status === "expired"}
        <div><h1 class="text-xl font-semibold tracking-[-0.025em] text-base-content">Password link expired</h1><p class="portal-copy mt-2 text-sm">This password request is missing or no longer active. Ask for a new link.</p></div>
      {:else if flowState?.status === "consumed"}
        <div><h1 class="text-xl font-semibold tracking-[-0.025em] text-base-content">Password link already used</h1><p class="portal-copy mt-2 text-sm">This {flowKindLabel(flowState.kind)} request has already been completed.</p></div>
      {:else if active}
        <div><h1 class="text-xl font-semibold tracking-[-0.025em] text-base-content">{title}</h1></div>
        {@render targetSummary()}
        {#if !isExpectedPasswordFlow(active)}<div class="alert alert-warning text-sm" role="alert"><span>This link is for {flowKindLabel(active.kind)}, not password setup or reset. Continue only if this is expected.</span></div>{/if}
        {#if supportsLocal}
          <form class="grid gap-4" onsubmit={(event) => { event.preventDefault(); void submitLocal(); }}>
            {#if !isResetFlow && fixedUsername}
              <label class="form-control gap-1.5"><span class="label-text text-sm font-medium text-base-content">Username</span><input class="input input-bordered w-full" autocomplete="username" disabled readonly value={fixedUsername} /></label>
            {/if}
            <label class="form-control gap-1.5">
              <span class="label-text text-sm font-medium text-base-content">Password</span>
              <input class="input input-bordered w-full" aria-describedby="password-help" autocomplete="new-password" disabled={submitting} minlength={passwordMinLength ?? undefined} required type="password" bind:value={password} />
              <span id="password-help" class:text-error={!!passwordCurrentError} class="text-xs text-base-content/65">{passwordHelp}</span>
            </label>
            <label class="form-control gap-1.5">
              <span class="label-text text-sm font-medium text-base-content">Confirm password</span>
              <input class="input input-bordered w-full" aria-describedby="confirm-help" autocomplete="new-password" disabled={submitting} required type="password" bind:value={confirmPassword} />
              <span id="confirm-help" class:text-error={!!confirmError} class="text-xs text-base-content/65">{confirmError ?? "Re-enter your password"}</span>
            </label>
            <label class="form-control gap-1.5"><span class="label-text text-sm font-medium text-base-content">Name <span class="font-normal text-base-content/65">optional</span></span><input class="input input-bordered w-full" autocomplete="name" disabled={submitting} bind:value={name} /></label>
            <label class="form-control gap-1.5"><span class="label-text text-sm font-medium text-base-content">Email <span class="font-normal text-base-content/65">optional</span></span><input class="input input-bordered w-full" autocomplete="email" disabled={submitting} type="email" bind:value={email} /></label>
            <button class="btn btn-primary btn-block" disabled={!canSubmit} type="submit">{#if submitting}<span class="loading loading-spinner loading-sm" aria-hidden="true"></span>Saving...{:else}{action}{/if}</button>
          </form>
        {:else}<div class="alert alert-info text-sm" role="alert"><span>This password request does not allow username and password setup.</span></div>{/if}
        {#each unavailableProviders(active) as provider (provider.id)}<div class="portal-subtle-panel rounded-box p-4 text-sm text-base-content/65"><p class="font-semibold text-base-content">{provider.displayName}</p><p class="portal-copy mt-1">OAuth account-flow completion is not available in the built-in portal yet.</p></div>{/each}
      {/if}
      {#if submitting}<p class="portal-copy text-sm" aria-live="polite">Submitting password request...</p>{/if}
      {#if error}<div class="alert alert-error text-sm" role="alert"><span>{error}</span></div>{/if}
    </div>
  </div>
</main>
