[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.6.0", features = ["derive"] }
miette = { version = "7.6.0", features = ["fancy"] }
serde_json = "1.0.149"
tokio = { version = "1.51.1", features = ["rt-multi-thread"] }
trellis-cli = { path = "../crates/cli", default-features = false }
trellis-codegen-ts = { path = "../crates/codegen-ts" }
trellis-codegen-rust = { path = "../crates/codegen-rust" }
trellis-idl = { path = "../crates/idl" }
trellis-protocol = { path = "../crates/protocol" }
wasm-bindgen-cli-support = "=0.2.125"

[dev-dependencies]
tempfile = "3.23.0"
