// Generated by Trellis. Do not edit.
import type { AppRequestDescriptor } from "@oatscenter/trellis/generated";
import * as Api0 from "../../apis/runtime/mod.js";
/** Developer selections and local State codecs; never principal installation evidence. */
export declare const request: AppRequestDescriptor & {
	readonly id: "runtime-trellis.Denied";
	readonly kind: "browser";
	readonly requiredCapabilities: readonly [];
	readonly optionalCapabilities: readonly [];
	readonly uses: readonly [{
		readonly api: typeof Api0.API;
		readonly actions: readonly [];
		readonly optionalCapabilities: readonly [];
	}];
	readonly states: {};
};
export type Request = typeof request;
export default request;
