// Generated by Trellis. Do not edit.
// @ts-self-types="./mod.d.ts"
import * as Api0 from "../../apis/runtime/mod.js";
/** Developer selections and local State codecs; never principal installation evidence. */
export const request = {
	id: "runtime-trellis.Denied",
	kind: "browser",
	requiredCapabilities: [],
	optionalCapabilities: [],
	uses: [{
		api: Api0.API,
		actions: [],
		optionalCapabilities: []
	}],
	states: {}
};
export default request;
