// Generated by Trellis. Do not edit.
import type { AppRequestDescriptor } from "@oatscenter/trellis/generated";
import * as Api0 from "../../apis/runtime/mod.js";
/** Developer selections and local State codecs; never principal installation evidence. */
export declare const request: AppRequestDescriptor & {
	readonly id: "runtime-trellis.Caller";
	readonly kind: "browser";
	readonly requiredCapabilities: readonly ["runtime-trellis.runtime@v1::transport"];
	readonly optionalCapabilities: readonly [];
	readonly uses: readonly [{
		readonly api: typeof Api0.API;
		readonly actions: readonly [{
			readonly descriptorName: "rpc:Echo";
			readonly direction: "call";
			readonly optionalCapabilities: readonly [];
		}, {
			readonly descriptorName: "operation:Upload";
			readonly direction: "invoke";
			readonly optionalCapabilities: readonly [];
		}, {
			readonly descriptorName: "operation:Work";
			readonly direction: "invoke";
			readonly optionalCapabilities: readonly [];
		}, {
			readonly descriptorName: "event:Changed";
			readonly direction: "publish";
			readonly optionalCapabilities: readonly [];
		}, {
			readonly descriptorName: "event:Changed";
			readonly direction: "subscribe";
			readonly optionalCapabilities: readonly [];
		}, {
			readonly descriptorName: "live:Watch";
			readonly direction: "subscribe";
			readonly optionalCapabilities: readonly [];
		}];
		readonly optionalCapabilities: readonly [];
	}];
	readonly states: {};
};
export type Request = typeof request;
export default request;
