// Generated by Trellis. Do not edit.
// @ts-self-types="./mod.d.ts"
import * as Api0 from "../../apis/runtime/mod.js";
/** Developer selections and local State codecs; never principal installation evidence. */
export const request = {
	id: "runtime-trellis.Caller",
	kind: "browser",
	requiredCapabilities: ["runtime-trellis.runtime@v1::transport"],
	optionalCapabilities: [],
	uses: [{
		api: Api0.API,
		actions: [
			{
				descriptorName: "rpc:Echo",
				direction: "call",
				optionalCapabilities: []
			},
			{
				descriptorName: "operation:Upload",
				direction: "invoke",
				optionalCapabilities: []
			},
			{
				descriptorName: "operation:Work",
				direction: "invoke",
				optionalCapabilities: []
			},
			{
				descriptorName: "event:Changed",
				direction: "publish",
				optionalCapabilities: []
			},
			{
				descriptorName: "event:Changed",
				direction: "subscribe",
				optionalCapabilities: []
			},
			{
				descriptorName: "live:Watch",
				direction: "subscribe",
				optionalCapabilities: []
			}
		],
		optionalCapabilities: []
	}],
	states: {}
};
export default request;
