// Generated by Trellis. Do not edit.
import type { AppRequestDescriptor } from "@oatscenter/trellis/generated";
import * as Api0 from "../../apis/orders/mod.js";
/** Developer selections and local State codecs; never principal installation evidence. */
export declare const request: AppRequestDescriptor & {
	readonly id: "acme-orders.OrdersCaller";
	readonly kind: "browser";
	readonly requiredCapabilities: readonly ["acme-orders.orders@v1::create"];
	readonly optionalCapabilities: readonly [];
	readonly uses: readonly [{
		readonly api: typeof Api0.API;
		readonly actions: readonly [{
			readonly descriptorName: "rpc:Create";
			readonly direction: "call";
			readonly optionalCapabilities: readonly [];
		}];
		readonly optionalCapabilities: readonly [];
	}];
	readonly states: {};
};
export type Request = typeof request;
export default request;
