// Generated by Trellis. Do not edit.
import * as Types0 from "../../types/_internal/p0.js";
export type DropAlphaInput = Types0.Empty;
export type DropAlphaOutput = Types0.Empty;
export type ObservedInput = Types0.Empty;
export type ObservedOutput = Types0.Observed;
export type AlphaEvent = Types0.Sample;
export type BetaEvent = Types0.Sample;
declare const __api: {
	readonly identity: "runtime-trellis.events@v1";
	readonly actions: {
		readonly "rpc:DropAlpha": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:DropAlpha";
			readonly input: typeof Types0.EmptyCodec;
			readonly output: typeof Types0.EmptyCodec;
			readonly errors: readonly [];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Observed": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Observed";
			readonly input: typeof Types0.EmptyCodec;
			readonly output: typeof Types0.ObservedCodec;
			readonly errors: readonly [];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "event:Alpha": {
			readonly kind: "event";
			readonly descriptorName: "event:Alpha";
			readonly payload: typeof Types0.SampleCodec;
			readonly parameters: readonly [];
		};
		readonly "event:Beta": {
			readonly kind: "event";
			readonly descriptorName: "event:Beta";
			readonly payload: typeof Types0.SampleCodec;
			readonly parameters: readonly [];
		};
	};
	readonly packageEvidence: unknown;
};
export declare const API: typeof __api;
export declare const API_DIGEST: "dMti0uEq-IqFayB8R-JYo0hlwi0tZ64jnmSirVEy_Tw";
export {};
