// Generated by Trellis. Do not edit.
// @ts-self-types="./mod.d.ts"
import * as Api0 from "../../apis/RuntimeTrellisEventsV1/mod.js";
/** Developer selections and local State codecs; never principal installation evidence. */
export const request = {
	id: "runtime-trellis.Beta",
	kind: "browser",
	requiredCapabilities: ["runtime-trellis.events@v1::publishBeta"],
	optionalCapabilities: [],
	uses: [{
		api: Api0.API,
		actions: [{
			descriptorName: "event:Beta",
			direction: "publish",
			optionalCapabilities: []
		}],
		optionalCapabilities: []
	}],
	states: {}
};
export default request;
