// Generated by Trellis. Do not edit.
// @ts-self-types="./mod.d.ts"
import * as Api0 from "../../apis/RuntimeTrellisEventsV1/mod.js";
/** Developer selections and local State codecs; never principal installation evidence. */
export const request = {
	id: "runtime-trellis.Alpha",
	kind: "browser",
	requiredCapabilities: [
		"runtime-trellis.events@v1::dropAlpha",
		"runtime-trellis.events@v1::inspect",
		"runtime-trellis.events@v1::publishAlpha"
	],
	optionalCapabilities: [],
	uses: [{
		api: Api0.API,
		actions: [
			{
				descriptorName: "rpc:DropAlpha",
				direction: "call",
				optionalCapabilities: []
			},
			{
				descriptorName: "rpc:Observed",
				direction: "call",
				optionalCapabilities: []
			},
			{
				descriptorName: "event:Alpha",
				direction: "publish",
				optionalCapabilities: []
			}
		],
		optionalCapabilities: []
	}],
	states: {}
};
export default request;
