// Generated by Trellis. Do not edit.
import type { AppRequestDescriptor } from "@oatscenter/trellis/generated";
import * as Api0 from "../../apis/RuntimeTrellisEventsV1/mod.js";
/** Developer selections and local State codecs; never principal installation evidence. */
export declare const request: AppRequestDescriptor & {
	readonly id: "runtime-trellis.Alpha";
	readonly kind: "browser";
	readonly requiredCapabilities: readonly ["runtime-trellis.events@v1::dropAlpha", "runtime-trellis.events@v1::inspect", "runtime-trellis.events@v1::publishAlpha"];
	readonly optionalCapabilities: readonly [];
	readonly uses: readonly [{
		readonly api: typeof Api0.API;
		readonly actions: readonly [{
			readonly descriptorName: "rpc:DropAlpha";
			readonly direction: "call";
			readonly optionalCapabilities: readonly [];
		}, {
			readonly descriptorName: "rpc:Observed";
			readonly direction: "call";
			readonly optionalCapabilities: readonly [];
		}, {
			readonly descriptorName: "event:Alpha";
			readonly direction: "publish";
			readonly optionalCapabilities: readonly [];
		}];
		readonly optionalCapabilities: readonly [];
	}];
	readonly states: {};
};
export type Request = typeof request;
export default request;
