// Generated by Trellis. Do not edit.
export type Value = {
	readonly revision: number;
	readonly value: string;
	readonly [key: string]: unknown;
};
export declare const ValueCodec: {
	decode(value: unknown): Value;
	encode(value: Value): unknown;
};
