// Generated by Trellis. Do not edit.
// @ts-self-types="./p0.d.ts"
import { codecs } from "@oatscenter/trellis/generated";
export const ValueCodec = codecs.recursive(() => codecs.named("client-upgrade-fixture.Value", codecs.model({
	revision: codecs.u32,
	value: codecs.string
})));
