// Generated by Trellis. Do not edit.
import * as Types0 from "../../types/_internal/p0.js";
export type CreateInput = Types0.CreateOrderRequest;
export type CreateOutput = Types0.CreateOrderResponse;
declare const __api: {
	readonly identity: "acme-orders.orders@v1";
	readonly actions: {
		readonly "rpc:Create": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Create";
			readonly input: typeof Types0.CreateOrderRequestCodec;
			readonly output: typeof Types0.CreateOrderResponseCodec;
			readonly errors: readonly [];
			readonly download: false;
			readonly pagination: undefined;
		};
	};
	readonly packageEvidence: unknown;
};
export declare const API: typeof __api;
export declare const API_DIGEST: "q3lUjFwlRq6kqh-O6tk3Y9IAt5_8Eza2oCVavB526G4";
export {};
