// Generated by Trellis. Do not edit.
import { TrellisError } from "@oatscenter/trellis/generated";
import type { SerializableErrorData } from "@oatscenter/trellis/generated";
import * as Types1 from "../../types/_internal/p1.js";
export type ConflictData = SerializableErrorData & {
	readonly type: "trellis.state@v1::Conflict";
} & Types1.StateConflict;
export declare class Conflict extends TrellisError<ConflictData> {
	static readonly type: "trellis.state@v1::Conflict";
	static readonly payloadCodec: typeof Types1.StateConflictCodec;
	readonly name: "Conflict";
	readonly data: ConflictData;
	constructor(data: ConflictData);
	static fromSerializable(data: unknown): Conflict;
	toSerializable(): ConflictData;
}
export type CorruptRepresentationData = SerializableErrorData & {
	readonly type: "trellis.state@v1::CorruptRepresentation";
} & Types1.StateRepresentationError;
export declare class CorruptRepresentation extends TrellisError<CorruptRepresentationData> {
	static readonly type: "trellis.state@v1::CorruptRepresentation";
	static readonly payloadCodec: typeof Types1.StateRepresentationErrorCodec;
	readonly name: "CorruptRepresentation";
	readonly data: CorruptRepresentationData;
	constructor(data: CorruptRepresentationData);
	static fromSerializable(data: unknown): CorruptRepresentation;
	toSerializable(): CorruptRepresentationData;
}
export type UnsupportedRepresentationData = SerializableErrorData & {
	readonly type: "trellis.state@v1::UnsupportedRepresentation";
} & Types1.StateRepresentationError;
export declare class UnsupportedRepresentation extends TrellisError<UnsupportedRepresentationData> {
	static readonly type: "trellis.state@v1::UnsupportedRepresentation";
	static readonly payloadCodec: typeof Types1.StateRepresentationErrorCodec;
	readonly name: "UnsupportedRepresentation";
	readonly data: UnsupportedRepresentationData;
	constructor(data: UnsupportedRepresentationData);
	static fromSerializable(data: unknown): UnsupportedRepresentation;
	toSerializable(): UnsupportedRepresentationData;
}
export type DeleteInput = Types1.StateDeleteRequest;
export type DeleteOutput = Types1.StateDeleteResponse;
export type GetInput = Types1.StateGetRequest;
export type GetOutput = Types1.StateGetResponse;
export type PutInput = Types1.StatePutRequest;
export type PutOutput = Types1.StatePutResponse;
export type ResourcesInspectInput = Types1.ResourcesInspectRequest;
export type ResourcesInspectOutput = Types1.ResourcesInspectResponse;
export type ResourcesQueryInput = Types1.ResourcesQueryRequest;
export type ResourcesQueryOutput = Types1.ResourcesQueryResponse;
declare const __api: {
	readonly identity: "trellis.state@v1";
	readonly actions: {
		readonly "rpc:Delete": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Delete";
			readonly input: typeof Types1.StateDeleteRequestCodec;
			readonly output: typeof Types1.StateDeleteResponseCodec;
			readonly errors: readonly [typeof Conflict];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Get": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Get";
			readonly input: typeof Types1.StateGetRequestCodec;
			readonly output: typeof Types1.StateGetResponseCodec;
			readonly errors: readonly [typeof CorruptRepresentation, typeof UnsupportedRepresentation];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Put": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Put";
			readonly input: typeof Types1.StatePutRequestCodec;
			readonly output: typeof Types1.StatePutResponseCodec;
			readonly errors: readonly [typeof Conflict, typeof CorruptRepresentation, typeof UnsupportedRepresentation];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Resources.Inspect": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Resources.Inspect";
			readonly input: typeof Types1.ResourcesInspectRequestCodec;
			readonly output: typeof Types1.ResourcesInspectResponseCodec;
			readonly errors: readonly [typeof CorruptRepresentation, typeof UnsupportedRepresentation];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Resources.Query": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Resources.Query";
			readonly input: typeof Types1.ResourcesQueryRequestCodec;
			readonly output: typeof Types1.ResourcesQueryResponseCodec;
			readonly errors: readonly [typeof CorruptRepresentation, typeof UnsupportedRepresentation];
			readonly download: false;
			readonly pagination: "cursor";
		};
	};
	readonly packageEvidence: unknown;
};
export declare const API: typeof __api;
export declare const API_DIGEST: "bqIK645jHWh6xBk0V8kejZI_2AWodtWsDwG0rawTvo8";
export {};
