// Generated by Trellis. Do not edit.
import * as Types0 from "../../types/_internal/p0.js";
export type EchoInput = Types0.Value;
export type EchoOutput = Types0.Value;
export type UploadInput = Types0.Value;
export type UploadOutput = Types0.Value;
export type WorkInput = Types0.Value;
export type WorkOutput = Types0.Value;
export type ChangedEvent = Types0.Value;
export type WatchInput = Types0.Empty;
export type WatchEvent = Types0.Value;
declare const __api: {
	readonly identity: "runtime-trellis.runtime@v1";
	readonly actions: {
		readonly "rpc:Echo": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Echo";
			readonly input: typeof Types0.ValueCodec;
			readonly output: typeof Types0.ValueCodec;
			readonly errors: readonly [];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "operation:Upload": {
			readonly kind: "operation";
			readonly descriptorName: "operation:Upload";
			readonly input: typeof Types0.ValueCodec;
			readonly output: typeof Types0.ValueCodec;
			readonly progress: undefined;
			readonly update: undefined;
			readonly errors: readonly [];
			readonly signals: {};
			readonly upload: true;
		};
		readonly "operation:Work": {
			readonly kind: "operation";
			readonly descriptorName: "operation:Work";
			readonly input: typeof Types0.ValueCodec;
			readonly output: typeof Types0.ValueCodec;
			readonly progress: undefined;
			readonly update: undefined;
			readonly errors: readonly [];
			readonly signals: {};
			readonly upload: false;
		};
		readonly "event:Changed": {
			readonly kind: "event";
			readonly descriptorName: "event:Changed";
			readonly payload: typeof Types0.ValueCodec;
			readonly parameters: readonly [];
		};
		readonly "feed:Watch": {
			readonly kind: "feed";
			readonly descriptorName: "feed:Watch";
			readonly input: typeof Types0.EmptyCodec;
			readonly event: typeof Types0.ValueCodec;
		};
	};
	readonly packageEvidence: unknown;
};
export declare const API: typeof __api;
export declare const API_DIGEST: "vFFD_x8YVvYflnnJHoHnBNSrsNmvYk2rx6bn59ZtuIY";
export {};
