// Generated by Trellis. Do not edit.
import { TrellisError } from "@oatscenter/trellis/generated";
import type { SerializableErrorData } from "@oatscenter/trellis/generated";
import * as Types1 from "../../types/_internal/p1.js";
export type UnexpectedErrorData = SerializableErrorData & {
	readonly type: "trellis.core@v1::UnexpectedError";
};
export declare class UnexpectedError extends TrellisError<UnexpectedErrorData> {
	static readonly type: "trellis.core@v1::UnexpectedError";
	readonly name: "UnexpectedError";
	readonly data: UnexpectedErrorData;
	constructor(data: UnexpectedErrorData);
	static fromSerializable(data: unknown): UnexpectedError;
	toSerializable(): UnexpectedErrorData;
}
export type ValidationErrorData = SerializableErrorData & {
	readonly type: "trellis.core@v1::ValidationError";
};
export declare class ValidationError extends TrellisError<ValidationErrorData> {
	static readonly type: "trellis.core@v1::ValidationError";
	readonly name: "ValidationError";
	readonly data: ValidationErrorData;
	constructor(data: ValidationErrorData);
	static fromSerializable(data: unknown): ValidationError;
	toSerializable(): ValidationErrorData;
}
export type ResourcesDestroyInput = Types1.ResourcesDestroyRequest;
export type ResourcesDestroyOutput = Types1.ResourcesDestroyResponse;
export type ResourcesInspectInput = Types1.ResourcesInspectRequest;
export type ResourcesInspectOutput = Types1.ResourcesInspectResponse;
export type ResourcesQueryInput = Types1.ResourcesQueryRequest;
export type ResourcesQueryOutput = Types1.ResourcesQueryResponse;
export type SurfaceStatusInput = Types1.TrellisSurfaceStatusRequest;
export type SurfaceStatusOutput = Types1.TrellisSurfaceStatusResponse;
declare const __api: {
	readonly identity: "trellis.core@v1";
	readonly actions: {
		readonly "rpc:Resources.Destroy": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Resources.Destroy";
			readonly input: typeof Types1.ResourcesDestroyRequestCodec;
			readonly output: typeof Types1.ResourcesDestroyResponseCodec;
			readonly errors: readonly [typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Resources.Inspect": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Resources.Inspect";
			readonly input: typeof Types1.ResourcesInspectRequestCodec;
			readonly output: typeof Types1.ResourcesInspectResponseCodec;
			readonly errors: readonly [typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Resources.Query": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Resources.Query";
			readonly input: typeof Types1.ResourcesQueryRequestCodec;
			readonly output: typeof Types1.ResourcesQueryResponseCodec;
			readonly errors: readonly [typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: "cursor";
		};
		readonly "rpc:Surface.Status": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Surface.Status";
			readonly input: typeof Types1.TrellisSurfaceStatusRequestCodec;
			readonly output: typeof Types1.TrellisSurfaceStatusResponseCodec;
			readonly errors: readonly [typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
	};
	readonly packageEvidence: unknown;
};
export declare const API: typeof __api;
export declare const API_DIGEST: "ort4pZPv8EIhAelwexctvEIJhNuNaWCZPtIDF4XVLXM";
export {};
