use std::path::PathBuf;

use trellis_runtime::{
    AuthConfig, AuthorizationConfig, ClientConfig, HttpConfig, LeasesConfig,
    LiveProviderSeedFilesConfig, LocalIdentityConfig, NatsAuthCalloutConfig, NatsConfig,
    NatsRuntimeConfig, OAuthConfig, PlatformTtlConfig, RuntimeConfig, StorageConfig,
    SubsystemConfig,
};

use crate::types::TrellisBootstrapOptions;

/// Render the Trellis runtime TOML config for a full bootstrap bundle.
///
/// # Panics
///
/// Panics if the internally-built runtime config cannot be serialized as TOML.
/// The config is assembled from TOML-compatible field types, so serialization
/// failure indicates a bug in this crate or in the runtime config model.
#[must_use]
pub fn render_trellis_config(options: &TrellisBootstrapOptions) -> String {
    let config = trellis_runtime_config(options);
    let rendered = toml::to_string_pretty(&config)
        .expect("serializing Trellis runtime config should not fail");
    format!("# Generated by `trellis init config`.\n{rendered}")
}

/// Build the shared Rust runtime config value for a bootstrap bundle.
#[must_use]
pub fn trellis_runtime_config(options: &TrellisBootstrapOptions) -> RuntimeConfig {
    RuntimeConfig {
        instance_name: Some(options.runtime.name.clone()),
        event_session_seed_file: Some(PathBuf::from("./session.seed")),
        event_context_digest_file: None,
        live_provider_seed_files: Some(LiveProviderSeedFilesConfig {
            platform: Some(PathBuf::from("./live-providers/platform.seed")),
            health: Some(PathBuf::from("./live-providers/health.seed")),
            jobs: Some(PathBuf::from("./live-providers/jobs.seed")),
            events: Some(PathBuf::from("./live-providers/events.seed")),
        }),
        paths: None,
        http: Some(HttpConfig {
            port: Some(options.runtime.trellis_port),
            bind_address: options.runtime.bind_address,
            public_origin: Some(options.runtime.public_origin.clone()),
            origins: Some({
                let mut origins = vec![options.runtime.public_origin.clone()];
                origins.extend(options.runtime.extra_origins.iter().cloned());
                origins
            }),
            allow_insecure_origins: Some({
                let mut origins = vec![options.runtime.public_origin.clone()];
                origins.extend(options.runtime.extra_origins.iter().cloned());
                origins
            }),
            web_source: options.runtime.web_source.clone(),
            portal_source: options.runtime.portal_source.clone(),
            console_source: options.runtime.console_source.clone(),
            rate_limit_max: Some(options.runtime.rate_limit_max),
            rate_limit_window_ms: Some(options.runtime.rate_limit_window_ms),
        }),
        nats: Some(NatsConfig {
            servers: Some(options.runtime.nats_server_url.clone()),
            runtime: Some(NatsRuntimeConfig {
                auth_creds_path: Some(PathBuf::from("./nats/creds/auth-auth.creds")),
                trellis_creds_path: Some(PathBuf::from("./nats/creds/trellis-auth.creds")),
                system_creds_path: Some(PathBuf::from("./nats/creds/system.creds")),
            }),
            auth_callout: Some(NatsAuthCalloutConfig {
                sentinel_public_key_file: Some(PathBuf::from("./nats/secrets/auth-sentinel.pub")),
                issuer_signing_seed_file: Some(PathBuf::from(
                    "./nats/secrets/auth-issuer-signing.seed",
                )),
                target_signing_seed_file: Some(PathBuf::from(
                    "./nats/secrets/auth-target-signing.seed",
                )),
                xkey_seed_file: Some(PathBuf::from("./nats/secrets/auth-sx.seed")),
            }),
        }),
        client: Some(ClientConfig {
            ws_nats_servers: Some(vec![options.runtime.nats_websocket_url.clone()]),
            nats_servers: Some(vec![options.runtime.nats_server_url.clone()]),
        }),
        leases: Some(LeasesConfig {
            bucket: Some("trellis_runtime_leases".to_string()),
            replicas: Some(1),
            ttl_ms: Some(30_000),
            renew_ms: Some(5_000),
        }),
        auth: Some(AuthConfig {
            local_identity: Some(LocalIdentityConfig {
                enabled: Some(true),
                password_min_length: Some(8),
            }),
            authorization: Some(AuthorizationConfig {
                issuer_signing_seed_file: PathBuf::from("./auth/authorization-issuer.seed"),
                context_lifetime_seconds: options
                    .runtime
                    .authorization
                    .context_lifetime_seconds
                    .unwrap_or(300),
                refresh_lead_seconds: options
                    .runtime
                    .authorization
                    .refresh_lead_seconds
                    .unwrap_or(60),
                refresh_jitter_seconds: options
                    .runtime
                    .authorization
                    .refresh_jitter_seconds
                    .unwrap_or(15),
                minimum_context_lifetime_seconds: options
                    .runtime
                    .authorization
                    .minimum_context_lifetime_seconds
                    .unwrap_or(76),
                maximum_bootstrap_jwt_lifetime_seconds: 3_600,
                allowed_clock_skew_seconds: 30,
                maximum_context_bytes: 65_536,
                maximum_permissions: 4_096,
                context_bucket: "trellis_authorization_contexts".to_owned(),
                registry_replicas: 1,
            }),
        }),
        oauth: Some(OAuthConfig {
            redirect_base: Some(format!(
                "{}/auth/callback",
                options.runtime.public_origin.trim_end_matches('/')
            )),
            always_show_provider_chooser: Some(false),
            providers: options.runtime.oauth_providers.clone(),
        }),
        platform: Some(SubsystemConfig {
            storage: Some(sqlite_storage()),
            history_retention_days: None,
            transport_retention_hours: None,
            transport_max_bytes: None,
            retention_days: None,
            ttl_ms: Some(PlatformTtlConfig {
                sessions: Some(options.runtime.ttl_ms.sessions.unwrap_or(86_400_000)),
                oauth: Some(options.runtime.ttl_ms.oauth.unwrap_or(300_000)),
                device_flow: Some(options.runtime.ttl_ms.device_flow.unwrap_or(1_800_000)),
                pending_auth: Some(options.runtime.ttl_ms.pending_auth.unwrap_or(300_000)),
            }),
        }),
        jobs: Some(SubsystemConfig {
            storage: Some(sqlite_storage()),
            history_retention_days: None,
            transport_retention_hours: None,
            transport_max_bytes: None,
            retention_days: None,
            ttl_ms: None,
        }),
        health: Some(SubsystemConfig {
            storage: Some(sqlite_storage()),
            history_retention_days: Some(30),
            transport_retention_hours: Some(24),
            transport_max_bytes: Some(1_073_741_824),
            retention_days: None,
            ttl_ms: None,
        }),
        events: Some(SubsystemConfig {
            storage: Some(sqlite_storage()),
            history_retention_days: None,
            transport_retention_hours: None,
            transport_max_bytes: None,
            retention_days: Some(7),
            ttl_ms: None,
        }),
    }
}

fn sqlite_storage() -> StorageConfig {
    StorageConfig {
        kind: "sqlite".to_string(),
        path: None,
        url: None,
        journal_mode: Some("wal".to_string()),
        busy_timeout_ms: Some(5_000),
        single_writer: Some(true),
    }
}
