[package]
name = "trellis-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Canonical protocol primitives for Trellis."

[lints]
workspace = true

[dependencies]
base64.workspace = true
ed25519-dalek.workspace = true
jsonptr.workspace = true
nkeys.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_json_canonicalizer.workspace = true
sha2.workspace = true
thiserror.workspace = true
time = { workspace = true, features = ["formatting", "parsing"] }
ulid = "1.2.1"

[dev-dependencies]
jsonptr = { workspace = true, features = ["json", "resolve"] }
