use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

use miette::{IntoDiagnostic, Result};
use trellis_idl::{
    api_digest, capability_consent_digest, participant_digest, selected_permission_atoms,
    ActionDefinition, ActionKind, PackageGraph, ParticipantDefinition, ParticipantKind,
    ResourceDefinition,
};
use trellis_protocol::PermissionAtom;

pub(crate) fn render(graph: &PackageGraph) -> Result<String> {
    let mut source = String::from(
        "// Generated by `cargo xtask install`. Do not edit.\n\
use std::collections::BTreeMap;\n\
use trellis_protocol::{ApiSurfaceKind, GrantSet, ParticipantKind, ParticipantResourceKind, PermissionAction, PermissionAtom, PermissionTarget};\n\
use super::evidence::{ActionRuntimeProjection, ApiRuntimeProjection, CapabilityRuntimeProjection, ParticipantRuntimeProjection, ResourceRuntimeProjection, RuntimeActionKind};\n\n\
pub(crate) struct BuiltinParticipant {\n\
    pub package_digest: &'static str,\n\
    pub participant_digest: &'static str,\n\
    pub needs_digest: &'static str,\n\
    pub projection: ParticipantRuntimeProjection,\n\
}\n\n\
pub(crate) fn participant(id: &str) -> Option<BuiltinParticipant> {\n\
    match id {\n",
    );
    for (index, participant) in graph.root_package().participants().values().enumerate() {
        writeln!(
            source,
            "        {:?} => Some(participant_{index}()),",
            participant.identity().as_str()
        )
        .into_diagnostic()?;
    }
    source.push_str("        _ => None,\n    }\n}\n\n");

    let api_indexes = graph
        .packages()
        .values()
        .flat_map(|package| package.apis().keys())
        .enumerate()
        .map(|(index, id)| (id.as_str().to_owned(), index))
        .collect::<BTreeMap<_, _>>();
    for (api_id, index) in &api_indexes {
        let api = graph
            .packages()
            .values()
            .find_map(|package| {
                package
                    .apis()
                    .iter()
                    .find(|(id, _)| id.as_str() == api_id)
                    .map(|(_, api)| api)
            })
            .expect("indexed API");
        render_api(&mut source, graph, api_id, *index, api)?;
    }
    for (index, participant) in graph.root_package().participants().values().enumerate() {
        render_participant(&mut source, graph, participant, index, &api_indexes)?;
    }
    source.push_str(
        "fn api_permission(api: &str, surface: ApiSurfaceKind, name: &str, action: PermissionAction) -> PermissionAtom {\n\
    PermissionAtom::new(PermissionTarget::api_surface(api, surface, name).expect(\"generated API target\"), action).expect(\"generated API permission\")\n\
}\n\n\
fn resource_permission(participant: &str, kind: ParticipantResourceKind, name: &str, action: PermissionAction) -> PermissionAtom {\n\
    PermissionAtom::new(PermissionTarget::participant_resource(participant, kind, name).expect(\"generated resource target\"), action).expect(\"generated resource permission\")\n\
}\n",
    );
    writeln!(
        source,
        "\npub(crate) const PACKAGE_DIGEST: &str = {:?};",
        graph.root_digest()
    )
    .into_diagnostic()?;
    Ok(source)
}

fn render_api(
    source: &mut String,
    graph: &PackageGraph,
    _api_id: &str,
    index: usize,
    api: &trellis_idl::ApiDefinition,
) -> Result<()> {
    writeln!(
        source,
        "fn api_{index}() -> ApiRuntimeProjection {{\n    ApiRuntimeProjection {{\n        digest: {:?}.into(),\n        major: {},\n        actions: BTreeMap::from([",
        api_digest(graph, api.identity())?,
        api.major()
    )
    .into_diagnostic()?;
    for (id, action) in api.actions() {
        let (kind, upload, download, event_parameter_count) = match action {
            ActionDefinition::Rpc { download, .. } => ("Rpc", false, *download, 0),
            ActionDefinition::Operation { upload, .. } => ("Operation", *upload, false, 0),
            ActionDefinition::Event { parameters, .. } => ("Event", false, false, parameters.len()),
            ActionDefinition::Live { .. } => ("Live", false, false, 0),
        };
        writeln!(
            source,
            "            ({:?}.into(), ActionRuntimeProjection {{ kind: RuntimeActionKind::{kind}, upload: {upload}, download: {download}, event_parameter_count: {event_parameter_count} }}),",
            format!("{}:{}", action_kind(id.kind), id.name)
        )
        .into_diagnostic()?;
    }
    source.push_str("        ]),\n        capabilities: BTreeMap::from([\n");
    for (id, capability) in api.capabilities() {
        writeln!(
            source,
            "            ({:?}.into(), CapabilityRuntimeProjection {{ display_name: {:?}.into(), description: {:?}.into(), consequence: {:?}.into(), consent_digest: {:?}.into(), public: {}, allows: vec![",
            id.as_str(), capability.title, capability.description, capability.consequence,
            capability_consent_digest(graph, id)?, capability.public
        )
        .into_diagnostic()?;
        for selection in &capability.allows {
            for atom in selected_permission_atoms(api.identity(), selection, api)? {
                writeln!(source, "                {},", render_permission(&atom))
                    .into_diagnostic()?;
            }
        }
        source.push_str("            ] }),\n");
    }
    source.push_str("        ]),\n    }\n}\n\n");
    Ok(())
}

fn render_participant(
    source: &mut String,
    graph: &PackageGraph,
    participant: &ParticipantDefinition,
    index: usize,
    api_indexes: &BTreeMap<String, usize>,
) -> Result<()> {
    let participant_id = participant.identity().as_str();
    let referenced = participant
        .implements()
        .iter()
        .map(|id| id.as_str())
        .chain(participant.uses().keys().map(|id| id.as_str()))
        .collect::<BTreeSet<_>>();
    let needs = graph
        .participant_needs(participant.identity())
        .expect("compiled participant needs");
    let required = needs
        .required_grants()
        .permissions()
        .iter()
        .map(render_permission)
        .collect::<Vec<_>>();
    let optional = needs
        .optional_grants()
        .iter()
        .map(|(name, grants)| {
            (
                name.clone(),
                grants
                    .permissions()
                    .iter()
                    .map(render_permission)
                    .collect::<Vec<_>>(),
            )
        })
        .collect::<BTreeMap<_, _>>();
    let required_capabilities = needs.required_capabilities();

    let mut resources = Vec::new();
    for (name, resource) in participant.resources() {
        let (projection, _) = resource_projection(graph, resource)?;
        resources.push((name.as_str(), projection));
    }

    writeln!(
        source,
        "fn participant_{index}() -> BuiltinParticipant {{\n    BuiltinParticipant {{\n        package_digest: PACKAGE_DIGEST,\n        participant_digest: {:?},\n        needs_digest: {:?},\n        projection: ParticipantRuntimeProjection {{\n            participant_id: {participant_id:?}.into(),\n            participant_kind: ParticipantKind::{},\n            display_name: {:?}.into(),\n            implemented_apis: BTreeMap::from([",
        participant_digest(graph, participant.identity())?,
        graph
            .participant_needs(participant.identity())
            .expect("compiled participant needs")
            .digest(),
        match participant.kind() {
            ParticipantKind::Service => "Service",
            ParticipantKind::Device => "Device",
            ParticipantKind::App => "App",
            ParticipantKind::Agent => "Agent",
        },
        participant.name()
    )
    .into_diagnostic()?;
    for api_id in participant.implements() {
        writeln!(
            source,
            "                ({:?}.into(), api_{}()),",
            api_id.as_str(),
            api_indexes[api_id.as_str()]
        )
        .into_diagnostic()?;
    }
    source.push_str("            ]),\n            referenced_apis: BTreeMap::from([\n");
    for api_id in &referenced {
        writeln!(
            source,
            "                ({api_id:?}.into(), api_{}()),",
            api_indexes[*api_id]
        )
        .into_diagnostic()?;
    }
    source.push_str("            ]),\n            resources: BTreeMap::from([\n");
    for (name, projection) in resources {
        writeln!(
            source,
            "                ({name:?}.into(), {}),",
            projection.render()
        )
        .into_diagnostic()?;
    }
    source.push_str("            ]),\n            required_grants: GrantSet::new(vec![\n");
    for atom in required {
        writeln!(source, "                {atom},").into_diagnostic()?;
    }
    source.push_str("            ]),\n            optional_grant_bundles: BTreeMap::from([\n");
    for (name, atoms) in &optional {
        writeln!(
            source,
            "                ({name:?}.into(), GrantSet::new(vec![{}])),",
            atoms.join(", ")
        )
        .into_diagnostic()?;
    }
    source.push_str("            ]),\n            required_capabilities: vec![\n");
    for capability in required_capabilities {
        writeln!(source, "                {:?}.into(),", capability.as_str()).into_diagnostic()?;
    }
    source.push_str(
        "            ],\n            optional_capability_definitions: BTreeMap::from([\n",
    );
    let optional_capabilities = participant
        .uses()
        .values()
        .flat_map(|selection| selection.optional_capabilities.iter())
        .map(|capability| capability.as_str())
        .collect::<BTreeSet<_>>();
    for (name, atoms) in optional
        .iter()
        .filter(|(name, _)| optional_capabilities.contains(name.as_str()))
    {
        writeln!(
            source,
            "                ({name:?}.into(), GrantSet::new(vec![{}])),",
            atoms.join(", ")
        )
        .into_diagnostic()?;
    }
    let (companion_participant_id, companion_participant_kind, companion_required) = participant
        .companion()
        .map_or(("None".to_owned(), "None".to_owned(), false), |companion| {
            let kind = graph
                .packages()
                .values()
                .find_map(|package| package.participants().get(&companion.participant))
                .expect("compiled companion participant")
                .kind();
            (
                format!("Some({:?}.into())", companion.participant.as_str()),
                format!("Some(ParticipantKind::{kind:?})"),
                !companion.optional,
            )
        });
    writeln!(
        source,
        "            ]),\n            companion_participant_id: {companion_participant_id},\n            companion_participant_kind: {companion_participant_kind},\n            companion_required: {companion_required},\n        }},\n    }}\n}}\n"
    )
    .into_diagnostic()?;
    Ok(())
}

fn render_permission(atom: &PermissionAtom) -> String {
    if let Some((api, surface, name)) = atom.target().as_api_surface() {
        return format!(
            "api_permission({api:?}, ApiSurfaceKind::{surface:?}, {name:?}, PermissionAction::{:?})",
            atom.action()
        );
    }
    if let Some((api, operation, signal)) = atom.target().as_operation_signal() {
        return format!(
            "PermissionAtom::new(PermissionTarget::operation_signal({api:?}, {operation:?}, {signal:?}).expect(\"generated signal target\"), PermissionAction::{:?}).expect(\"generated signal permission\")",
            atom.action()
        );
    }
    if let Some((participant, kind, name)) = atom.target().as_participant_resource() {
        return format!(
            "resource_permission({participant:?}, ParticipantResourceKind::{kind:?}, {name:?}, PermissionAction::{:?})",
            atom.action()
        );
    }
    unreachable!("participant needs contain an unsupported permission target")
}

struct ResourceProjection {
    kind: &'static str,
    optional: bool,
    title: String,
    description: String,
    representation: Option<String>,
    history: Option<u64>,
    ttl_ms: Option<u64>,
    desired_max_value: Option<u64>,
    desired_max_object: Option<u64>,
    desired_max_total: Option<u64>,
    deadline_ms: Option<u64>,
    payload_schema: Option<String>,
    result_schema: Option<String>,
    update_schema: Option<String>,
    job_key_path: Option<Vec<String>>,
    job_key_policy: Option<String>,
    retry_attempts: Option<u32>,
    retry_backoff_ms: Vec<u64>,
    consumer_events: BTreeMap<String, Vec<String>>,
    consumer_concurrency: Option<u32>,
    consumer_replay_all: bool,
}

impl ResourceProjection {
    fn render(&self) -> String {
        format!(
            "ResourceRuntimeProjection {{ kind: ParticipantResourceKind::{}, optional: {}, title: {:?}.into(), description: {:?}.into(), representation: {}, history: {:?}, ttl_ms: {:?}, desired_max_value: {:?}, desired_max_object: {:?}, desired_max_total: {:?}, deadline_ms: {:?}, payload_schema: {}, result_schema: {}, update_schema: {}, job_key_path: {:?}, job_key_policy: {}, retry_attempts: {:?}, retry_backoff_ms: vec!{:?}, consumer_events: BTreeMap::from([{}]), consumer_concurrency: {:?}, consumer_replay_all: {} }}",
            self.kind,
            self.optional,
            self.title,
            self.description,
            self.representation.as_deref().unwrap_or("None"),
            self.history,
            self.ttl_ms,
            self.desired_max_value,
            self.desired_max_object,
            self.desired_max_total,
            self.deadline_ms,
            option_string(&self.payload_schema),
            option_string(&self.result_schema),
            option_string(&self.update_schema),
            self.job_key_path,
            option_string(&self.job_key_policy),
            self.retry_attempts,
            self.retry_backoff_ms,
            self.consumer_events.iter().map(|(api, events)| format!("({api:?}.into(), vec!{:?}.into_iter().map(str::to_owned).collect())", events)).collect::<Vec<_>>().join(", "),
            self.consumer_concurrency,
            self.consumer_replay_all,
        )
    }
}

fn resource_projection(
    graph: &PackageGraph,
    resource: &ResourceDefinition,
) -> Result<(ResourceProjection, Vec<&'static str>)> {
    let mut projection = ResourceProjection {
        kind: "State",
        optional: false,
        title: String::new(),
        description: String::new(),
        representation: None,
        history: None,
        ttl_ms: None,
        desired_max_value: None,
        desired_max_object: None,
        desired_max_total: None,
        deadline_ms: None,
        payload_schema: None,
        result_schema: None,
        update_schema: None,
        job_key_path: None,
        job_key_policy: None,
        retry_attempts: None,
        retry_backoff_ms: Vec::new(),
        consumer_events: BTreeMap::new(),
        consumer_concurrency: None,
        consumer_replay_all: false,
    };
    let actions = match resource {
        ResourceDefinition::State {
            optional,
            docs,
            schema,
            version,
            accepts,
        } => {
            projection.optional = *optional;
            projection.title.clone_from(&docs.title);
            projection.description.clone_from(&docs.description);
            projection.representation =
                Some(render_representation(graph, schema, *version, accepts)?);
            vec!["Read", "Write", "Delete"]
        }
        ResourceDefinition::Kv {
            optional,
            docs,
            history,
            ttl_ms,
            desired_max_value,
            schema,
            version,
            accepts,
            ..
        } => {
            projection.kind = "Kv";
            projection.optional = *optional;
            projection.title.clone_from(&docs.title);
            projection.description.clone_from(&docs.description);
            projection.history = Some(*history);
            projection.ttl_ms = Some(*ttl_ms);
            projection.desired_max_value = *desired_max_value;
            projection.representation =
                Some(render_representation(graph, schema, *version, accepts)?);
            vec!["Read", "Write", "Delete"]
        }
        ResourceDefinition::Store {
            optional,
            docs,
            ttl_ms,
            desired_max_object,
            desired_max_total,
            ..
        } => {
            projection.kind = "Store";
            projection.optional = *optional;
            projection.title.clone_from(&docs.title);
            projection.description.clone_from(&docs.description);
            projection.ttl_ms = Some(*ttl_ms);
            projection.desired_max_object = *desired_max_object;
            projection.desired_max_total = *desired_max_total;
            vec!["Read", "Write", "Delete"]
        }
        ResourceDefinition::Job {
            optional,
            docs,
            payload,
            result,
            update,
            key_concurrency,
            ..
        } => {
            projection.kind = "JobQueue";
            projection.optional = *optional;
            projection.title.clone_from(&docs.title);
            projection.description.clone_from(&docs.description);
            projection.payload_schema = Some(payload.id.as_str().to_owned());
            projection.result_schema = result.as_ref().map(|value| value.id.as_str().to_owned());
            projection.update_schema = update.as_ref().map(|value| value.id.as_str().to_owned());
            if let Some(key_concurrency) = key_concurrency {
                projection.job_key_path = Some(key_concurrency.path.clone());
                projection.job_key_policy = Some(
                    match key_concurrency.policy {
                        trellis_idl::KeyConcurrencyPolicy::Queue => "queue",
                        trellis_idl::KeyConcurrencyPolicy::Reject => "reject",
                        trellis_idl::KeyConcurrencyPolicy::Supersede => "supersede",
                    }
                    .to_owned(),
                );
            }
            vec!["Submit", "Process"]
        }
        ResourceDefinition::Consumer {
            optional,
            docs,
            events,
            concurrency,
            replay,
            retry,
            ..
        } => {
            projection.kind = "EventConsumer";
            projection.optional = *optional;
            projection.title.clone_from(&docs.title);
            projection.description.clone_from(&docs.description);
            projection.consumer_concurrency = Some(*concurrency);
            projection.consumer_replay_all = matches!(replay, trellis_idl::Replay::All);
            for (api, event) in events {
                projection
                    .consumer_events
                    .entry(api.as_str().to_owned())
                    .or_default()
                    .push(event.clone());
            }
            if let Some(retry) = retry {
                projection.retry_attempts = Some(retry.attempts);
                projection.retry_backoff_ms = retry.backoff_ms.clone();
            }
            vec!["Consume"]
        }
    };
    Ok((projection, actions))
}

fn render_representation(
    graph: &PackageGraph,
    schema: &trellis_idl::TypeRef,
    version: u32,
    accepts: &[trellis_idl::HistoricRepresentation],
) -> Result<String> {
    let schema =
        serde_json::to_string(&trellis_idl::json_schema(graph, schema)?).into_diagnostic()?;
    let accepts = accepts
        .iter()
        .map(|accepted| {
            Ok(format!(
                "({}, serde_json::from_str({:?}).expect(\"generated representation schema\"))",
                accepted.version,
                serde_json::to_string(&trellis_idl::json_schema(graph, &accepted.ty)?)
                    .into_diagnostic()?
            ))
        })
        .collect::<Result<Vec<_>>>()?;
    Ok(format!(
        "Some(super::evidence::ResourceRepresentationRuntimeProjection {{ schema: serde_json::from_str({schema:?}).expect(\"generated representation schema\"), version: {version}, accepts: BTreeMap::from([{}]) }})",
        accepts.join(", ")
    ))
}

fn option_string(value: &Option<String>) -> String {
    value
        .as_ref()
        .map_or_else(|| "None".into(), |value| format!("Some({value:?}.into())"))
}

fn action_kind(kind: ActionKind) -> &'static str {
    match kind {
        ActionKind::Rpc => "rpc",
        ActionKind::Operation => "operation",
        ActionKind::Event => "event",
        ActionKind::Live => "live",
    }
}
