// Generated by Trellis. Do not edit.
export type Empty = {
	readonly [key: string]: unknown;
};
export declare const EmptyCodec: {
	decode(value: unknown): Empty;
	encode(value: Empty): unknown;
};
export type Observed = {
	readonly values: Array<string>;
	readonly [key: string]: unknown;
};
export declare const ObservedCodec: {
	decode(value: unknown): Observed;
	encode(value: Observed): unknown;
};
export type ResourceValue = {
	readonly value: string;
	readonly [key: string]: unknown;
};
export declare const ResourceValueCodec: {
	decode(value: unknown): ResourceValue;
	encode(value: ResourceValue): unknown;
};
export type Sample = {
	readonly site: string;
	readonly value: string;
	readonly [key: string]: unknown;
};
export declare const SampleCodec: {
	decode(value: unknown): Sample;
	encode(value: Sample): unknown;
};
export type Saved = {
	readonly value: string;
	readonly [key: string]: unknown;
};
export declare const SavedCodec: {
	decode(value: unknown): Saved;
	encode(value: Saved): unknown;
};
export type Value = {
	readonly value: string;
	readonly [key: string]: unknown;
};
export declare const ValueCodec: {
	decode(value: unknown): Value;
	encode(value: Value): unknown;
};
