// Generated by Trellis. Do not edit.
// @ts-self-types="./p0.d.ts"
import { codecs } from "@oatscenter/trellis/generated";
export const EmptyCodec = codecs.recursive(() => codecs.named("runtime-trellis.Empty", codecs.model({})));
export const ObservedCodec = codecs.recursive(() => codecs.named("runtime-trellis.Observed", codecs.model({ values: codecs.list(codecs.string) })));
export const ResourceValueCodec = codecs.recursive(() => codecs.named("runtime-trellis.ResourceValue", codecs.model({ value: codecs.string })));
export const SampleCodec = codecs.recursive(() => codecs.named("runtime-trellis.Sample", codecs.model({
	site: codecs.string,
	value: codecs.string
})));
export const SavedCodec = codecs.recursive(() => codecs.named("runtime-trellis.Saved", codecs.model({ value: codecs.string })));
export const ValueCodec = codecs.recursive(() => codecs.named("runtime-trellis.Value", codecs.model({ value: codecs.string })));
