// Generated by Trellis. Do not edit.
import type { ParticipantJobsFromResources, ParticipantKvFromResources, RuntimeApiFromGenerated } from "@oatscenter/trellis/generated";
import * as types from "./types.js";
export { types };
import * as Api0 from "../../apis/orders/mod.js";
type __ActionNames = {
	readonly "acme-orders.orders@v1:rpc:Create": "Create";
};
type __Resources = {};
declare const __participant: {
	readonly digest: string;
	readonly requiredCapabilities: readonly Readonly<{
		id: string;
		consentDigest: string;
	}>[];
	readonly requiredGrants: readonly Readonly<{
		action: string;
		target: Readonly<Record<string, unknown>>;
	}>[];
	readonly kind: "app";
	readonly id: "acme-orders.OrdersCaller";
	readonly identity: "acme-orders.OrdersCaller";
	readonly path: "OrdersCaller";
	readonly implements: readonly [];
	readonly uses: readonly [{
		readonly api: typeof Api0.API;
		readonly actions: readonly [{
			readonly descriptorName: "rpc:Create";
			readonly direction: "call";
			readonly optionalCapabilities: readonly [];
		}];
		readonly optionalCapabilities: readonly [];
	}];
	readonly optionalGrants: Readonly<Record<string, readonly Readonly<{
		action: string;
		target: Readonly<Record<string, unknown>>;
	}>[]>>;
	readonly actionNames: __ActionNames;
	readonly resources: __Resources;
	readonly __runtimeTypes?: {
		readonly ownedApi: RuntimeApiFromGenerated<never, __ActionNames>;
		readonly api: RuntimeApiFromGenerated<typeof Api0.API, __ActionNames>;
		readonly jobs: ParticipantJobsFromResources<__Resources>;
		readonly kv: ParticipantKvFromResources<__Resources>;
	};
	readonly packageEvidence: unknown;
};
export declare const participant: {
	readonly kind: typeof __participant.kind;
	readonly id: typeof __participant.id;
	readonly identity: typeof __participant.identity;
	readonly path: typeof __participant.path;
	readonly digest: typeof __participant.digest;
	readonly requiredGrants: typeof __participant.requiredGrants;
	readonly requiredCapabilities: typeof __participant.requiredCapabilities;
	readonly implements: typeof __participant.implements;
	readonly uses: typeof __participant.uses;
	readonly optionalGrants: typeof __participant.optionalGrants;
	readonly actionNames: typeof __participant.actionNames;
	readonly resources: typeof __participant.resources;
	readonly __runtimeTypes?: typeof __participant.__runtimeTypes;
	readonly packageEvidence: unknown;
};
export declare const PARTICIPANT_DIGEST: "s8I-Qjr78Y7LIyxro2m6WtFikWvqkfGNlgccy5ZxRfw";
export type Participant = typeof participant;
export type ResourceDescriptors = typeof participant.resources;
export type ResourceHandles<Handles extends { readonly [Name in keyof ResourceDescriptors] : unknown }> = { readonly [Name in keyof ResourceDescriptors as ResourceDescriptors[Name]["availability"] extends "required" ? Name : never] : Handles[Name] } & { readonly [Name in keyof ResourceDescriptors as ResourceDescriptors[Name]["availability"] extends "optional" ? Name : never] : Handles[Name] | undefined };
export type Availability = Readonly<{
	resources: Readonly<{}>;
	capabilities: Readonly<{}>;
}>;
export type ParticipantFacade<Handles extends { readonly [Name in keyof ResourceDescriptors] : unknown }> = Readonly<{
	participant: Participant;
	resources: ResourceHandles<Handles>;
	availability(): Availability;
	watchAvailability(): AsyncIterable<Availability>;
}>;
export default participant;
