// Generated by Trellis. Do not edit.
import { TrellisError } from "@oatscenter/trellis/generated";
import type { SerializableErrorData } from "@oatscenter/trellis/generated";
import * as Types1 from "../../types/_internal/p1.js";
export type NotFoundErrorData = SerializableErrorData & {
	readonly type: "trellis.jobs@v1::NotFoundError";
} & Types1.JobsNotFoundErrorData;
export declare class NotFoundError extends TrellisError<NotFoundErrorData> {
	static readonly type: "trellis.jobs@v1::NotFoundError";
	static readonly payloadCodec: typeof Types1.JobsNotFoundErrorDataCodec;
	readonly name: "NotFoundError";
	readonly data: NotFoundErrorData;
	constructor(data: NotFoundErrorData);
	static fromSerializable(data: unknown): NotFoundError;
	toSerializable(): NotFoundErrorData;
}
export type UnexpectedErrorData = SerializableErrorData & {
	readonly type: "trellis.jobs@v1::UnexpectedError";
};
export declare class UnexpectedError extends TrellisError<UnexpectedErrorData> {
	static readonly type: "trellis.jobs@v1::UnexpectedError";
	readonly name: "UnexpectedError";
	readonly data: UnexpectedErrorData;
	constructor(data: UnexpectedErrorData);
	static fromSerializable(data: unknown): UnexpectedError;
	toSerializable(): UnexpectedErrorData;
}
export type ValidationErrorData = SerializableErrorData & {
	readonly type: "trellis.jobs@v1::ValidationError";
};
export declare class ValidationError extends TrellisError<ValidationErrorData> {
	static readonly type: "trellis.jobs@v1::ValidationError";
	readonly name: "ValidationError";
	readonly data: ValidationErrorData;
	constructor(data: ValidationErrorData);
	static fromSerializable(data: unknown): ValidationError;
	toSerializable(): ValidationErrorData;
}
export type CancelInput = Types1.JobsCancelRequest;
export type CancelOutput = Types1.JobsCancelResponse;
export type DismissDLQInput = Types1.JobsDismissDLQRequest;
export type DismissDLQOutput = Types1.JobsDismissDLQResponse;
export type GetKeyInput = Types1.JobsGetKeyRequest;
export type GetKeyOutput = Types1.JobsGetKeyResponse;
export type InspectInput = Types1.JobsInspectRequest;
export type InspectOutput = Types1.JobsInspectResponse;
export type ListDLQInput = Types1.JobsListDLQRequest;
export type ListDLQOutput = Types1.JobsListDLQResponse;
export type ListServicesInput = Types1.JobsListServicesRequest;
export type ListServicesOutput = Types1.JobsListServicesResponse;
export type MetricsInput = Types1.JobsMetricsRequest;
export type MetricsOutput = Types1.JobsMetricsResponse;
export type QueryInput = Types1.JobsQueryRequest;
export type QueryOutput = Types1.JobsQueryResponse;
export type ReplayDLQInput = Types1.JobsReplayDLQRequest;
export type ReplayDLQOutput = Types1.JobsReplayDLQResponse;
export type RetryInput = Types1.JobsRetryRequest;
export type RetryOutput = Types1.JobsRetryResponse;
export type SummaryInput = Types1.JobsSummaryRequest;
export type SummaryOutput = Types1.JobsSummaryResponse;
export type WatchInput = Types1.JobsWatchRequest;
export type WatchEvent = Types1.JobsWatchFrame;
declare const __api: {
	readonly identity: "trellis.jobs@v1";
	readonly actions: {
		readonly "rpc:Cancel": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Cancel";
			readonly input: typeof Types1.JobsCancelRequestCodec;
			readonly output: typeof Types1.JobsCancelResponseCodec;
			readonly errors: readonly [typeof NotFoundError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:DismissDLQ": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:DismissDLQ";
			readonly input: typeof Types1.JobsDismissDLQRequestCodec;
			readonly output: typeof Types1.JobsDismissDLQResponseCodec;
			readonly errors: readonly [typeof NotFoundError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:GetKey": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:GetKey";
			readonly input: typeof Types1.JobsGetKeyRequestCodec;
			readonly output: typeof Types1.JobsGetKeyResponseCodec;
			readonly errors: readonly [typeof NotFoundError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Inspect": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Inspect";
			readonly input: typeof Types1.JobsInspectRequestCodec;
			readonly output: typeof Types1.JobsInspectResponseCodec;
			readonly errors: readonly [typeof NotFoundError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:ListDLQ": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:ListDLQ";
			readonly input: typeof Types1.JobsListDLQRequestCodec;
			readonly output: typeof Types1.JobsListDLQResponseCodec;
			readonly errors: readonly [typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: "cursor";
		};
		readonly "rpc:ListServices": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:ListServices";
			readonly input: typeof Types1.JobsListServicesRequestCodec;
			readonly output: typeof Types1.JobsListServicesResponseCodec;
			readonly errors: readonly [typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: "cursor";
		};
		readonly "rpc:Metrics": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Metrics";
			readonly input: typeof Types1.JobsMetricsRequestCodec;
			readonly output: typeof Types1.JobsMetricsResponseCodec;
			readonly errors: readonly [typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Query": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Query";
			readonly input: typeof Types1.JobsQueryRequestCodec;
			readonly output: typeof Types1.JobsQueryResponseCodec;
			readonly errors: readonly [typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: "cursor";
		};
		readonly "rpc:ReplayDLQ": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:ReplayDLQ";
			readonly input: typeof Types1.JobsReplayDLQRequestCodec;
			readonly output: typeof Types1.JobsReplayDLQResponseCodec;
			readonly errors: readonly [typeof NotFoundError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Retry": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Retry";
			readonly input: typeof Types1.JobsRetryRequestCodec;
			readonly output: typeof Types1.JobsRetryResponseCodec;
			readonly errors: readonly [typeof NotFoundError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Summary": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Summary";
			readonly input: typeof Types1.JobsSummaryRequestCodec;
			readonly output: typeof Types1.JobsSummaryResponseCodec;
			readonly errors: readonly [typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "feed:Watch": {
			readonly kind: "feed";
			readonly descriptorName: "feed:Watch";
			readonly input: typeof Types1.JobsWatchRequestCodec;
			readonly event: typeof Types1.JobsWatchFrameCodec;
		};
	};
	readonly packageEvidence: unknown;
};
export declare const API: typeof __api;
export declare const API_DIGEST: "pgIp9PftLViyn-1-PKqw2kkCsEWAJYHurAEA158ylso";
export {};
