// Generated by Trellis. Do not edit.
import type { ParticipantJobsFromResources, ParticipantKvFromResources, RuntimeApiFromGenerated } from "@oats-center/trellis/generated";
import * as types from "./types.js";
export { types };
import * as Api0 from "../../apis/RuntimeTrellisEventsV1/mod.js";
type __ActionNames = {
	readonly "runtime-trellis.events@v1:rpc:DropAlpha": "DropAlpha";
	readonly "runtime-trellis.events@v1:rpc:Observed": "Observed";
	readonly "runtime-trellis.events@v1:event:Alpha": "Alpha";
	readonly "runtime-trellis.events@v1:event:Beta": "Beta";
};
type __Resources = {};
declare const __participant: {
	readonly kind: "service";
	readonly id: "runtime-trellis.EventService";
	readonly identity: "runtime-trellis.EventService";
	readonly path: "EventService";
	readonly implements: readonly [typeof Api0.API];
	readonly uses: readonly [];
	readonly actionNames: __ActionNames;
	readonly resources: __Resources;
	readonly __runtimeTypes?: {
		readonly ownedApi: RuntimeApiFromGenerated<typeof Api0.API, __ActionNames>;
		readonly api: RuntimeApiFromGenerated<typeof Api0.API, __ActionNames>;
		readonly jobs: ParticipantJobsFromResources<__Resources>;
		readonly kv: ParticipantKvFromResources<__Resources>;
	};
	readonly packageEvidence: unknown;
};
export declare const participant: {
	readonly kind: typeof __participant.kind;
	readonly id: typeof __participant.id;
	readonly identity: typeof __participant.identity;
	readonly path: typeof __participant.path;
	readonly implements: typeof __participant.implements;
	readonly uses: typeof __participant.uses;
	readonly actionNames: typeof __participant.actionNames;
	readonly resources: typeof __participant.resources;
	readonly __runtimeTypes?: typeof __participant.__runtimeTypes;
	readonly packageEvidence: unknown;
};
export declare const PARTICIPANT_DIGEST: "j3jBufyAmyOJAD2H-781574cN9k6zii5NbGTyjVmvn0";
export type Participant = typeof participant;
export type ResourceDescriptors = typeof participant.resources;
export type ResourceHandles<Handles extends { readonly [Name in keyof ResourceDescriptors] : unknown }> = { readonly [Name in keyof ResourceDescriptors as ResourceDescriptors[Name]["availability"] extends "required" ? Name : never] : Handles[Name] } & { readonly [Name in keyof ResourceDescriptors as ResourceDescriptors[Name]["availability"] extends "optional" ? Name : never] : Handles[Name] | undefined };
export type Availability = Readonly<{
	resources: Readonly<{}>;
	capabilities: Readonly<{}>;
}>;
export type ParticipantFacade<Handles extends { readonly [Name in keyof ResourceDescriptors] : unknown }> = Readonly<{
	participant: Participant;
	resources: ResourceHandles<Handles>;
	availability(): Availability;
	watchAvailability(): AsyncIterable<Availability>;
}>;
export default participant;
