// Generated by Trellis. Do not edit.
import type { ParticipantJobsFromResources, ParticipantKvFromResources, RuntimeApiFromGenerated } from "@oatscenter/trellis/generated";
import * as types from "./types.js";
export { types };
import * as Api0 from "../../apis/upgrade/mod.js";
type __ActionNames = {
	readonly "client-upgrade-fixture.upgrade@v1:rpc:Echo": "Echo";
	readonly "client-upgrade-fixture.upgrade@v1:rpc:Extra": "Extra";
};
type __Resources = {};
declare const __participant: {
	readonly digest: string;
	readonly requiredCapabilities: readonly Readonly<{
		id: string;
		consentDigest: string;
	}>[];
	readonly requiredGrants: readonly Readonly<{
		action: string;
		target: Readonly<Record<string, unknown>>;
	}>[];
	readonly kind: "service";
	readonly id: "client-upgrade-fixture.Provider";
	readonly identity: "client-upgrade-fixture.Provider";
	readonly path: "Provider";
	readonly implements: readonly [typeof Api0.API];
	readonly uses: readonly [];
	readonly optionalGrants: Readonly<Record<string, readonly Readonly<{
		action: string;
		target: Readonly<Record<string, unknown>>;
	}>[]>>;
	readonly actionNames: __ActionNames;
	readonly resources: __Resources;
	readonly __runtimeTypes?: {
		readonly ownedApi: RuntimeApiFromGenerated<typeof Api0.API, __ActionNames>;
		readonly api: RuntimeApiFromGenerated<typeof Api0.API, __ActionNames>;
		readonly jobs: ParticipantJobsFromResources<__Resources>;
		readonly kv: ParticipantKvFromResources<__Resources>;
	};
	readonly packageEvidence: unknown;
};
export declare const participant: {
	readonly kind: typeof __participant.kind;
	readonly id: typeof __participant.id;
	readonly identity: typeof __participant.identity;
	readonly path: typeof __participant.path;
	readonly digest: typeof __participant.digest;
	readonly requiredGrants: typeof __participant.requiredGrants;
	readonly requiredCapabilities: typeof __participant.requiredCapabilities;
	readonly implements: typeof __participant.implements;
	readonly uses: typeof __participant.uses;
	readonly optionalGrants: typeof __participant.optionalGrants;
	readonly actionNames: typeof __participant.actionNames;
	readonly resources: typeof __participant.resources;
	readonly __runtimeTypes?: typeof __participant.__runtimeTypes;
	readonly packageEvidence: unknown;
};
export declare const PARTICIPANT_DIGEST: "dvHR82SHVd78ZYl0bJarMpnOAi2rlK-WmveY0bWY594";
export type Participant = typeof participant;
export type ResourceDescriptors = typeof participant.resources;
export type ResourceHandles<Handles extends { readonly [Name in keyof ResourceDescriptors] : unknown }> = { readonly [Name in keyof ResourceDescriptors as ResourceDescriptors[Name]["availability"] extends "required" ? Name : never] : Handles[Name] } & { readonly [Name in keyof ResourceDescriptors as ResourceDescriptors[Name]["availability"] extends "optional" ? Name : never] : Handles[Name] | undefined };
export type Availability = Readonly<{
	resources: Readonly<{}>;
	capabilities: Readonly<{}>;
}>;
export type ParticipantFacade<Handles extends { readonly [Name in keyof ResourceDescriptors] : unknown }> = Readonly<{
	participant: Participant;
	resources: ResourceHandles<Handles>;
	availability(): Availability;
	watchAvailability(): AsyncIterable<Availability>;
}>;
export default participant;
