// Generated by Trellis. Do not edit.
import * as Types0 from "../../types/_internal/p0.js";
export type EchoInput = Types0.Value;
export type EchoOutput = Types0.Value;
export type ExtraInput = Types0.Value;
export type ExtraOutput = Types0.Value;
declare const __api: {
	readonly identity: "client-upgrade-fixture.upgrade@v1";
	readonly actions: {
		readonly "rpc:Echo": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Echo";
			readonly input: typeof Types0.ValueCodec;
			readonly output: typeof Types0.ValueCodec;
			readonly errors: readonly [];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Extra": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Extra";
			readonly input: typeof Types0.ValueCodec;
			readonly output: typeof Types0.ValueCodec;
			readonly errors: readonly [];
			readonly download: false;
			readonly pagination: undefined;
		};
	};
	readonly packageEvidence: unknown;
};
export declare const API: typeof __api;
export declare const API_DIGEST: "hrtkJPffAT2UaYjBv7MHPk4ca9UaDOJIUw9CXNsyuX0";
export {};
