<script lang="ts">
  import { browser } from "$app/environment";
  import { onMount } from "svelte";
  import { getOrCreatePortalBinding } from "@qlever-llc/trellis/auth/browser";
  import PortalBrand from "$lib/components/PortalBrand.svelte";
  import { trellisUrl } from "$lib/portal_config";
  import {
    adminBootstrapFlowId,
    accountFlowProviderLoginUrl,
    completeAdminBootstrap,
    hasLocalProvider,
    loadAccountFlowState,
    parseAccountFlowOAuthCompletion,
    unavailableProviders,
    type AccountFlowState,
    type AdminBootstrapSuccess,
  } from "./page_state";

  let username = $state("");
  let password = $state("");
  let confirmPassword = $state("");
  let name = $state("");
  let email = $state("");
  let flowId = $state<string | null>(null);
  let browserFlowId = $state<string | null>(null);
  let portalBindingDigest = $state<string | null>(null);
  let flowState = $state.raw<AccountFlowState | null>(null);
  let loading = $state(true);
  let error = $state<string | null>(null);
  let submitting = $state(false);
  let completion = $state<AdminBootstrapSuccess | null>(null);

  const active = $derived(flowState?.status === "active" ? flowState : null);
  const loadedTerminalFlow = $derived(flowState?.status === "expired" || flowState?.status === "consumed");
  const localAvailable = $derived(active ? hasLocalProvider(active) : flowState === null);
  const passwordsMatch = $derived(password.length > 0 && password === confirmPassword);
  const confirmError = $derived(confirmPassword.length > 0 && !passwordsMatch ? "Passwords do not match" : null);
  const canSubmit = $derived(
    Boolean(flowId) && !loadedTerminalFlow && localAvailable && username.trim().length > 0 && password.length > 0 && passwordsMatch && !submitting && !completion,
  );

  function currentFlowId(): string | null {
    if (!browser) return null;
    return adminBootstrapFlowId(new URL(window.location.href));
  }

  function currentOAuthCompletion(): AdminBootstrapSuccess | null {
    if (!browser) return null;
    const completionState = parseAccountFlowOAuthCompletion(new URL(window.location.href));
    return completionState ? { status: "created", userId: completionState.userId } : null;
  }

  function refreshFlowId(): string | null {
    flowId = currentFlowId();
    if (!flowId) {
      error = "Missing bootstrap flow id. Open the bootstrap link generated by Trellis.";
    }
    return flowId;
  }

  async function loadFlow(): Promise<void> {
    const oauthCompletion = currentOAuthCompletion();
    if (oauthCompletion) {
      flowId = currentFlowId();
      completion = oauthCompletion;
      loading = false;
      error = null;
      return;
    }

    const activeFlowId = refreshFlowId();
    if (!activeFlowId) {
      loading = false;
      return;
    }

    loading = true;
    error = null;
    try {
      flowState = await loadAccountFlowState(trellisUrl, activeFlowId);
      if (flowState.status === "active") {
        username = flowState.username ?? username;
        name = flowState.target?.name ?? name;
        email = flowState.target?.email ?? email;
      }
    } catch (caught) {
      error = caught instanceof Error ? caught.message : String(caught);
    } finally {
      loading = false;
    }
  }

  async function submitBootstrap(): Promise<void> {
    const activeFlowId = refreshFlowId();
    if (!activeFlowId || loadedTerminalFlow) return;

    submitting = true;
    error = null;

    try {
      completion = await completeAdminBootstrap(trellisUrl, activeFlowId, {
        username: username.trim(),
        password,
        name,
        email,
        ...(browserFlowId ? { browserFlowId } : {}),
        ...(portalBindingDigest ? { portalBindingDigest } : {}),
      });
      if (completion.browserFlowId) {
        window.location.replace(
          `/login?flowId=${encodeURIComponent(completion.browserFlowId)}`,
        );
      }
    } catch (caught) {
      error = caught instanceof Error ? caught.message : String(caught);
    } finally {
      submitting = false;
    }
  }

  onMount(async () => {
    browserFlowId = new URL(window.location.href).searchParams.get("browserFlowId");
    if (browserFlowId) {
      portalBindingDigest = (
        await getOrCreatePortalBinding(browserFlowId, sessionStorage)
      ).digest;
    }
    void loadFlow();
  });
</script>

<svelte:head>
  <title>Bootstrap admin · Trellis</title>
</svelte:head>

<main
  class="portal-shell flex min-h-screen justify-center px-4 py-10 sm:px-6"
  data-theme="portal"
>
  <div class="portal-page w-full max-w-md">
    <header class="portal-header">
      <PortalBrand subtitle="Admin bootstrap" />
    </header>
    <div class="portal-body">

      {#if loading}
        <div class="flex items-center gap-4 py-3" aria-live="polite">
          <span class="loading loading-ring loading-lg" aria-hidden="true"></span>
          <div>
            <p class="text-sm font-medium text-base-content">Loading bootstrap</p>
            <p class="portal-copy text-xs">Resolving account-flow state.</p>
          </div>
        </div>
      {:else if completion}
        <div>
          <h1 class="text-xl font-semibold tracking-[-0.025em] text-base-content">Admin account ready</h1>
          <p class="portal-copy mt-2 text-sm">
            The administrator account is ready.
          </p>
        </div>

        <a class="btn btn-primary w-full" href="/console">Open admin console</a>
      {:else if flowState?.status === "expired"}
        <div>
          <h1 class="text-xl font-semibold tracking-[-0.025em] text-base-content">Bootstrap link expired</h1>
          <p class="portal-copy mt-2 text-sm">
            This admin bootstrap request is missing or no longer active. Start bootstrap again.
          </p>
        </div>
      {:else if flowState?.status === "consumed"}
        <div>
          <h1 class="text-xl font-semibold tracking-[-0.025em] text-base-content">Bootstrap already used</h1>
          <p class="portal-copy mt-2 text-sm">
            This admin bootstrap request has already been completed.
          </p>
        </div>
      {:else}
        <div>
          <h1 class="text-xl font-semibold tracking-[-0.025em] text-base-content">
            {active?.mode === "edit" ? "Edit the administrator" : "Create the administrator"}
          </h1>
          <p class="portal-copy mt-2 text-sm">
            {active?.mode === "edit"
              ? "Change the built-in administrator username and password. Existing sessions will be revoked."
              : "Choose local credentials for the built-in administrator account."}
          </p>
        </div>

        {#if active}
          {#each unavailableProviders(active) as provider (provider.id)}
            <a
              class="btn btn-outline btn-block"
              href={accountFlowProviderLoginUrl(
                trellisUrl,
                active.flowId,
                provider.id,
                browserFlowId && portalBindingDigest
                  ? { browserFlowId, portalBindingDigest }
                  : undefined,
              )}
            >
              Continue with {provider.displayName}
            </a>
          {/each}
        {/if}

        {#if active && !hasLocalProvider(active)}
          <div class="alert alert-info text-sm" role="alert">
            <span>This bootstrap request does not allow username and password setup.</span>
          </div>
        {:else}

        <form
          class="grid gap-4"
          onsubmit={(event) => {
            event.preventDefault();
            void submitBootstrap();
          }}
        >
          <label class="form-control gap-1.5">
            <span class="label-text text-sm font-medium text-base-content">Username</span>
            <input
              class="input input-bordered w-full"
              autocomplete="username"
              disabled={submitting || !flowId}
              required
              bind:value={username}
            />
          </label>

          <label class="form-control gap-1.5">
            <span class="label-text text-sm font-medium text-base-content">Password</span>
            <input
              class="input input-bordered w-full"
              autocomplete="new-password"
              disabled={submitting || !flowId}
              required
              type="password"
              bind:value={password}
            />
          </label>

          <label class="form-control gap-1.5">
            <span class="label-text text-sm font-medium text-base-content">Confirm password</span>
            <input
              class="input input-bordered w-full"
              autocomplete="new-password"
              disabled={submitting || !flowId}
              required
              type="password"
              bind:value={confirmPassword}
            />
            <span class:text-error={!!confirmError} class="text-xs text-base-content/65">{confirmError ?? "Re-enter your password"}</span>
          </label>

          <label class="form-control gap-1.5">
            <span class="label-text text-sm font-medium text-base-content">Name <span class="font-normal text-base-content/65">optional</span></span>
            <input
              class="input input-bordered w-full"
              autocomplete="name"
              disabled={submitting || !flowId}
              bind:value={name}
            />
          </label>

          <label class="form-control gap-1.5">
            <span class="label-text text-sm font-medium text-base-content">Email <span class="font-normal text-base-content/65">optional</span></span>
            <input
              class="input input-bordered w-full"
              autocomplete="email"
              disabled={submitting || !flowId}
              type="email"
              bind:value={email}
            />
          </label>

          <button class="btn btn-primary btn-block" disabled={!canSubmit} type="submit">
            {#if submitting}
              <span class="loading loading-spinner loading-sm" aria-hidden="true"></span>
              Saving administrator...
            {:else}
              {active?.mode === "edit" ? "Update administrator" : "Create administrator"}
            {/if}
          </button>
        </form>
        {/if}
      {/if}

      {#if submitting}
        <p class="portal-copy text-sm" aria-live="polite">Submitting admin bootstrap...</p>
      {/if}

      {#if error}
        <div class="alert alert-error text-sm" role="alert">
          <span>{error}</span>
        </div>
      {/if}
    </div>
  </div>
</main>
