[package]
name = "trellis-server"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Trellis server process orchestration."
publish = false

[lints]
workspace = true

[dependencies]
clap.workspace = true
miette.workspace = true
libc = "0.2.186"
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
opentelemetry_sdk.workspace = true
tracing-opentelemetry.workspace = true
trellis-bootstrap = { path = "../bootstrap", version = "0.100.0" }
trellis-local-nats = { path = "../local-nats", version = "0.100.0" }
trellis-runtime = { path = "../runtime", version = "0.100.0" }
trellis-rs = { path = "../trellis", version = "0.100.0", features = ["telemetry-otlp"] }

[dev-dependencies]
tempfile = "3.27.0"

[[bin]]
name = "trellis-server"
path = "src/main.rs"
