<script lang="ts">
  import { browser } from "$app/environment";
  import { onMount } from "svelte";
  import PortalBrand from "$lib/components/PortalBrand.svelte";
  import { trellisUrl } from "$lib/portal_config";
  import {
    accountFlowIdFromUrl,
    accountFlowProviderLoginUrl,
    completeAccountFlowLocalPassword,
    defaultProfileValue,
    flowKindLabel,
    hasLocalProvider,
    isExpectedLinkFlow,
    loadAccountFlowState,
    parseAccountFlowOAuthCompletion,
    unavailableProviders,
    type AccountFlowState,
    type LocalPasswordSuccess,
  } from "./page_state";

  let flowId = $state<string | null>(null);
  let flowState = $state.raw<AccountFlowState | null>(null);
  let loading = $state(true);
  let submitting = $state(false);
  let error = $state<string | null>(null);
  let completion = $state<LocalPasswordSuccess | null>(null);
  let username = $state("");
  let password = $state("");
  let name = $state("");
  let email = $state("");
  let defaultsApplied = false;

  const active = $derived(flowState?.status === "active" ? flowState : null);
  const localProviderAvailable = $derived(Boolean(active && hasLocalProvider(active)));
  const oidcProviders = $derived(active ? unavailableProviders(active) : []);
  const canSubmit = $derived(Boolean(active && flowId && localProviderAvailable && username.trim() && password && !submitting && !completion));

  function currentFlowId(): string | null {
    if (!browser) return null;
    return accountFlowIdFromUrl(new URL(window.location.href));
  }

  function currentOAuthCompletion(): LocalPasswordSuccess | null {
    if (!browser) return null;
    const completionState = parseAccountFlowOAuthCompletion(new URL(window.location.href));
    return completionState
      ? {
        status: "created",
        userId: completionState.userId,
        ...(completionState.returnTo ? { returnTo: completionState.returnTo } : {}),
      }
      : null;
  }

  function redirectToReturnTarget(target: string | undefined): boolean {
    if (!browser || !target) return false;
    window.location.assign(target);
    return true;
  }

  function applyDefaults(): void {
    if (!active || defaultsApplied) return;
    name = defaultProfileValue(active, "name");
    email = defaultProfileValue(active, "email");
    defaultsApplied = true;
  }

  function providerLinkAttributes(providerId: string): { href: string } {
    if (!active) return { href: "" };
    return { href: accountFlowProviderLoginUrl(trellisUrl, active.flowId, providerId) };
  }

  async function loadFlow(): Promise<void> {
    const oauthCompletion = currentOAuthCompletion();
    if (oauthCompletion) {
      flowId = currentFlowId();
      completion = oauthCompletion;
      loading = false;
      error = null;
      redirectToReturnTarget(oauthCompletion.returnTo);
      return;
    }

    flowId = currentFlowId();
    if (!flowId) {
      error = "Missing account-link flow id. Open the account-link URL generated by Trellis.";
      loading = false;
      return;
    }
    loading = true;
    error = null;
    try {
      flowState = await loadAccountFlowState(trellisUrl, flowId);
      applyDefaults();
    } catch (caught) {
      error = caught instanceof Error ? caught.message : String(caught);
    } finally {
      loading = false;
    }
  }

  async function submitLocal(): Promise<void> {
    if (!flowId || !active) return;
    submitting = true;
    error = null;
    try {
      const success = await completeAccountFlowLocalPassword(trellisUrl, flowId, {
        username: username.trim(),
        password,
        name,
        email,
      });
      completion = success;
      password = "";
      redirectToReturnTarget(success.returnTo);
    } catch (caught) {
      error = caught instanceof Error ? caught.message : String(caught);
    } finally {
      submitting = false;
    }
  }

  onMount(() => {
    if (!browser) return;
    void loadFlow();
  });
</script>

<svelte:head><title>Link account · Trellis</title></svelte:head>

{#snippet targetSummary()}
  {#if active?.target}
    <section class="portal-subtle-panel rounded-box p-4 text-sm leading-6">
      <p class="portal-section-label">Target account</p>
      <p class="mt-1 font-semibold text-base-content">{active.target.name ?? active.target.email ?? active.target.userId}</p>
      {#if active.target.email && active.target.email !== active.target.name}<p class="portal-copy">{active.target.email}</p>{/if}
      <p class="mono mt-1 break-all text-xs text-base-content/65">{active.target.userId}</p>
    </section>
  {/if}
{/snippet}

<main class="portal-shell flex min-h-screen justify-center px-4 py-10 sm:px-6" data-theme="portal">
  <div class="portal-page w-full max-w-md">
    <header class="portal-header"><PortalBrand subtitle="Account link" /></header>
    <div class="portal-body">
      {#if loading}
        <div class="flex items-center gap-4 py-3" aria-live="polite"><span class="loading loading-ring loading-lg" aria-hidden="true"></span><div><p class="text-sm font-medium text-base-content">Loading account link</p><p class="portal-copy text-xs">Resolving account-flow state.</p></div></div>
      {:else if completion}
        <div><h1 class="text-xl font-semibold tracking-[-0.025em] text-base-content">Account linked</h1><p class="portal-copy mt-2 text-sm">Your identity was linked to your Trellis account.</p></div>
        <div class="portal-subtle-panel rounded-box p-4 text-sm leading-6 text-base-content/70"><p class="portal-section-label">Canonical user</p><p class="mono mt-1 break-all text-base-content">{completion.userId}</p></div>
      {:else if flowState?.status === "expired"}
        <div><h1 class="text-xl font-semibold tracking-[-0.025em] text-base-content">Link expired</h1><p class="portal-copy mt-2 text-sm">This account-link request is missing or no longer active. Ask for a new link.</p></div>
      {:else if flowState?.status === "consumed"}
        <div><h1 class="text-xl font-semibold tracking-[-0.025em] text-base-content">Link already used</h1><p class="portal-copy mt-2 text-sm">This {flowKindLabel(flowState.kind)} request has already been completed.</p></div>
      {:else if active}
        {#if localProviderAvailable}
          <div><h1 class="text-xl font-semibold tracking-[-0.025em] text-base-content">Link local credentials</h1><p class="portal-copy mt-2 text-sm">Choose username and password credentials or continue with an external sign-in provider.</p></div>
        {:else}
          <div><h1 class="text-xl font-semibold tracking-[-0.025em] text-base-content">Link another account</h1><p class="portal-copy mt-2 text-sm">Choose an available sign-in provider to attach to the target Trellis account.</p></div>
        {/if}
        {@render targetSummary()}
        {#if !isExpectedLinkFlow(active)}<div class="alert alert-warning text-sm" role="alert"><span>This link is for {flowKindLabel(active.kind)}, not account linking. Continue only if this is expected.</span></div>{/if}
        {#if localProviderAvailable}
          <form class="grid gap-4" onsubmit={(event) => { event.preventDefault(); void submitLocal(); }}>
            <label class="form-control gap-1.5"><span class="label-text text-sm font-medium text-base-content">Username</span><input class="input input-bordered w-full" autocomplete="username" disabled={submitting} required bind:value={username} /></label>
            <label class="form-control gap-1.5"><span class="label-text text-sm font-medium text-base-content">Password</span><input class="input input-bordered w-full" autocomplete="new-password" disabled={submitting} required type="password" bind:value={password} /></label>
            <label class="form-control gap-1.5"><span class="label-text text-sm font-medium text-base-content">Name <span class="font-normal text-base-content/65">optional</span></span><input class="input input-bordered w-full" autocomplete="name" disabled={submitting} bind:value={name} /></label>
            <label class="form-control gap-1.5"><span class="label-text text-sm font-medium text-base-content">Email <span class="font-normal text-base-content/65">optional</span></span><input class="input input-bordered w-full" autocomplete="email" disabled={submitting} type="email" bind:value={email} /></label>
            <button class="btn btn-primary btn-block" disabled={!canSubmit} type="submit">{#if submitting}<span class="loading loading-spinner loading-sm" aria-hidden="true"></span>Linking...{:else}Link credentials{/if}</button>
          </form>
        {/if}
        {#each oidcProviders as provider (provider.id)}<a class="btn btn-outline btn-block" {...providerLinkAttributes(provider.id)}>Continue with {provider.displayName}</a>{/each}
        {#if !localProviderAvailable && oidcProviders.length === 0}<div class="alert alert-info text-sm" role="alert"><span>No sign-in providers are available for this account-link request.</span></div>{/if}
      {/if}
      {#if submitting}<p class="portal-copy text-sm" aria-live="polite">Submitting account link...</p>{/if}
      {#if error}<div class="alert alert-error text-sm" role="alert"><span>{error}</span></div>{/if}
    </div>
  </div>
</main>
