// Generated by Trellis. Do not edit.
import type { ParticipantJobsFromResources, ParticipantKvFromResources, RuntimeApiFromGenerated } from "@qlever-llc/trellis/generated";
import * as types from "./types.js";
export { types };
import * as Api0 from "../../apis/runtime/mod.js";
type __ActionNames = {
	readonly "runtime-trellis.runtime@v1:rpc:Echo": "Echo";
	readonly "runtime-trellis.runtime@v1:operation:Upload": "Upload";
	readonly "runtime-trellis.runtime@v1:operation:Work": "Work";
	readonly "runtime-trellis.runtime@v1:event:Changed": "Changed";
	readonly "runtime-trellis.runtime@v1:feed:Watch": "Watch";
};
type __Resources = {};
declare const __participant: {
	readonly kind: "app";
	readonly id: "runtime-trellis.Denied";
	readonly identity: "runtime-trellis.Denied";
	readonly path: "Denied";
	readonly implements: readonly [];
	readonly uses: readonly [{
		readonly api: typeof Api0.API;
		readonly actions: readonly [];
		readonly optionalCapabilities: readonly [];
	}];
	readonly actionNames: __ActionNames;
	readonly resources: __Resources;
	readonly __runtimeTypes?: {
		readonly ownedApi: RuntimeApiFromGenerated<never, __ActionNames>;
		readonly api: RuntimeApiFromGenerated<typeof Api0.API, __ActionNames>;
		readonly jobs: ParticipantJobsFromResources<__Resources>;
		readonly kv: ParticipantKvFromResources<__Resources>;
	};
	readonly packageEvidence: unknown;
};
export declare const participant: {
	readonly kind: typeof __participant.kind;
	readonly id: typeof __participant.id;
	readonly identity: typeof __participant.identity;
	readonly path: typeof __participant.path;
	readonly implements: typeof __participant.implements;
	readonly uses: typeof __participant.uses;
	readonly actionNames: typeof __participant.actionNames;
	readonly resources: typeof __participant.resources;
	readonly __runtimeTypes?: typeof __participant.__runtimeTypes;
	readonly packageEvidence: unknown;
};
export declare const PARTICIPANT_DIGEST: "6CArPir9rsBOVok7Ohw999Y5ikYDBOzvQMgK-yrIgys";
export type Participant = typeof participant;
export type ResourceDescriptors = typeof participant.resources;
export type ResourceHandles<Handles extends { readonly [Name in keyof ResourceDescriptors] : unknown }> = { readonly [Name in keyof ResourceDescriptors as ResourceDescriptors[Name]["availability"] extends "required" ? Name : never] : Handles[Name] } & { readonly [Name in keyof ResourceDescriptors as ResourceDescriptors[Name]["availability"] extends "optional" ? Name : never] : Handles[Name] | undefined };
export type Availability = Readonly<{
	resources: Readonly<{}>;
	capabilities: Readonly<{}>;
}>;
export type ParticipantFacade<Handles extends { readonly [Name in keyof ResourceDescriptors] : unknown }> = Readonly<{
	participant: Participant;
	resources: ResourceHandles<Handles>;
	availability(): Availability;
	watchAvailability(): AsyncIterable<Availability>;
}>;
export default participant;
