// Generated by Trellis. Do not edit.
import { TrellisError } from "@oatscenter/trellis/generated";
import type { SerializableErrorData } from "@oatscenter/trellis/generated";
import * as Types1 from "../../types/_internal/p1.js";
export type AuthErrorData = SerializableErrorData & {
	readonly type: "trellis.auth@v1::AuthError";
} & Types1.AuthErrorDetails;
export declare class AuthError extends TrellisError<AuthErrorData> {
	static readonly type: "trellis.auth@v1::AuthError";
	static readonly payloadCodec: typeof Types1.AuthErrorDetailsCodec;
	readonly name: "AuthError";
	readonly data: AuthErrorData;
	constructor(data: AuthErrorData);
	static fromSerializable(data: unknown): AuthError;
	toSerializable(): AuthErrorData;
}
export type UnexpectedErrorData = SerializableErrorData & {
	readonly type: "trellis.auth@v1::UnexpectedError";
} & Types1.AuthErrorDetails;
export declare class UnexpectedError extends TrellisError<UnexpectedErrorData> {
	static readonly type: "trellis.auth@v1::UnexpectedError";
	static readonly payloadCodec: typeof Types1.AuthErrorDetailsCodec;
	readonly name: "UnexpectedError";
	readonly data: UnexpectedErrorData;
	constructor(data: UnexpectedErrorData);
	static fromSerializable(data: unknown): UnexpectedError;
	toSerializable(): UnexpectedErrorData;
}
export type ValidationErrorData = SerializableErrorData & {
	readonly type: "trellis.auth@v1::ValidationError";
} & Types1.AuthErrorDetails;
export declare class ValidationError extends TrellisError<ValidationErrorData> {
	static readonly type: "trellis.auth@v1::ValidationError";
	static readonly payloadCodec: typeof Types1.AuthErrorDetailsCodec;
	readonly name: "ValidationError";
	readonly data: ValidationErrorData;
	constructor(data: ValidationErrorData);
	static fromSerializable(data: unknown): ValidationError;
	toSerializable(): ValidationErrorData;
}
export type CapabilitiesListInput = Types1.AuthCapabilitiesListRequest;
export type CapabilitiesListOutput = Types1.AuthCapabilitiesListResponse;
export type CapabilityGroupsDeleteInput = Types1.AuthCapabilityGroupsDeleteRequest;
export type CapabilityGroupsDeleteOutput = Types1.AuthCapabilityGroupsDeleteResponse;
export type CapabilityGroupsGetInput = Types1.AuthCapabilityGroupsGetRequest;
export type CapabilityGroupsGetOutput = Types1.AuthCapabilityGroupsGetResponse;
export type CapabilityGroupsListInput = Types1.AuthCapabilityGroupsListRequest;
export type CapabilityGroupsListOutput = Types1.AuthCapabilityGroupsListResponse;
export type CapabilityGroupsPutInput = Types1.AuthCapabilityGroupsPutRequest;
export type CapabilityGroupsPutOutput = Types1.AuthCapabilityGroupsPutResponse;
export type ConnectionsKickInput = Types1.AuthConnectionsKickRequest;
export type ConnectionsKickOutput = Types1.AuthConnectionsKickResponse;
export type ConnectionsListInput = Types1.AuthConnectionsListRequest;
export type ConnectionsListOutput = Types1.AuthConnectionsListResponse;
export type DeploymentsApplyInput = Types1.AuthDeploymentsApplyRequest;
export type DeploymentsApplyOutput = Types1.AuthDeploymentsApplyResponse;
export type DeploymentsCreateInput = Types1.AuthDeploymentsCreateRequest;
export type DeploymentsCreateOutput = Types1.AuthDeploymentsCreateResponse;
export type DeploymentsDisableInput = Types1.AuthDeploymentsDisableRequest;
export type DeploymentsDisableOutput = Types1.AuthDeploymentsDisableResponse;
export type DeploymentsEnableInput = Types1.AuthDeploymentsEnableRequest;
export type DeploymentsEnableOutput = Types1.AuthDeploymentsEnableResponse;
export type DeploymentsGetInput = Types1.AuthDeploymentsGetRequest;
export type DeploymentsGetOutput = Types1.AuthDeploymentsGetResponse;
export type DeploymentsListInput = Types1.AuthDeploymentsListRequest;
export type DeploymentsListOutput = Types1.AuthDeploymentsListResponse;
export type DeploymentsRemoveInput = Types1.AuthDeploymentsRemoveRequest;
export type DeploymentsRemoveOutput = Types1.AuthDeploymentsRemoveResponse;
export type DeviceUserAuthoritiesListInput = Types1.AuthDeviceUserAuthoritiesListRequest;
export type DeviceUserAuthoritiesListOutput = Types1.AuthDeviceUserAuthoritiesListResponse;
export type DeviceUserAuthoritiesReviewsDecideInput = Types1.AuthDeviceUserAuthoritiesReviewsDecideRequest;
export type DeviceUserAuthoritiesReviewsDecideOutput = Types1.AuthDeviceUserAuthoritiesReviewsDecideResponse;
export type DeviceUserAuthoritiesReviewsListInput = Types1.AuthDeviceUserAuthoritiesReviewsListRequest;
export type DeviceUserAuthoritiesReviewsListOutput = Types1.AuthDeviceUserAuthoritiesReviewsListResponse;
export type DeviceUserAuthoritiesRevokeInput = Types1.AuthDeviceUserAuthoritiesRevokeRequest;
export type DeviceUserAuthoritiesRevokeOutput = Types1.AuthDeviceUserAuthoritiesRevokeResponse;
export type DevicesDisableInput = Types1.AuthDevicesDisableRequest;
export type DevicesDisableOutput = Types1.AuthDevicesDisableResponse;
export type DevicesEnableInput = Types1.AuthDevicesEnableRequest;
export type DevicesEnableOutput = Types1.AuthDevicesEnableResponse;
export type DevicesListInput = Types1.AuthDevicesListRequest;
export type DevicesListOutput = Types1.AuthDevicesListResponse;
export type DevicesProvisionInput = Types1.AuthDevicesProvisionRequest;
export type DevicesProvisionOutput = Types1.AuthDevicesProvisionResponse;
export type DevicesRemoveInput = Types1.AuthDevicesRemoveRequest;
export type DevicesRemoveOutput = Types1.AuthDevicesRemoveResponse;
export type GrantsGetInput = Types1.AuthGrantsGetRequest;
export type GrantsGetOutput = Types1.AuthGrantsGetResponse;
export type GrantsListInput = Types1.AuthGrantsListRequest;
export type GrantsListOutput = Types1.AuthGrantsListResponse;
export type GrantsRevokeInput = Types1.AuthGrantsRevokeRequest;
export type GrantsRevokeOutput = Types1.AuthGrantsMutationResponse;
export type GrantsSetInput = Types1.AuthGrantsSetRequest;
export type GrantsSetOutput = Types1.AuthGrantsMutationResponse;
export type IssuersRevokeInput = Types1.AuthIssuersRevokeRequest;
export type IssuersRevokeOutput = Types1.AuthIssuersRevokeResponse;
export type ParticipantsGetInput = Types1.AuthParticipantsGetRequest;
export type ParticipantsGetOutput = Types1.AuthParticipantsGetResponse;
export type ParticipantsInstallInput = Types1.AuthParticipantsInstallRequest;
export type ParticipantsInstallOutput = Types1.AuthParticipantsInstallResponse;
export type ParticipantsListInput = Types1.AuthParticipantsListRequest;
export type ParticipantsListOutput = Types1.AuthParticipantsListResponse;
export type PortalsGetInput = Types1.AuthPortalsGetRequest;
export type PortalsGetOutput = Types1.AuthPortalsGetResponse;
export type PortalsGrantOverridesListInput = Types1.AuthPortalsGrantOverridesListRequest;
export type PortalsGrantOverridesListOutput = Types1.AuthPortalsGrantOverridesListResponse;
export type PortalsGrantOverridesPutInput = Types1.AuthPortalsGrantOverridesPutRequest;
export type PortalsGrantOverridesPutOutput = Types1.AuthPortalsGrantOverridesPutResponse;
export type PortalsGrantOverridesRemoveInput = Types1.AuthPortalsGrantOverridesRemoveRequest;
export type PortalsGrantOverridesRemoveOutput = Types1.AuthPortalsGrantOverridesRemoveResponse;
export type PortalsListInput = Types1.AuthPortalsListRequest;
export type PortalsListOutput = Types1.AuthPortalsListResponse;
export type PortalsLoginSettingsGetInput = Types1.AuthPortalsLoginSettingsGetRequest;
export type PortalsLoginSettingsGetOutput = Types1.AuthPortalsLoginSettingsGetResponse;
export type PortalsLoginSettingsUpdateInput = Types1.AuthPortalsLoginSettingsUpdateRequest;
export type PortalsLoginSettingsUpdateOutput = Types1.AuthPortalsLoginSettingsUpdateResponse;
export type PortalsPutInput = Types1.AuthPortalsPutRequest;
export type PortalsPutOutput = Types1.AuthPortalsPutResponse;
export type PortalsRemoveInput = Types1.AuthPortalsRemoveRequest;
export type PortalsRemoveOutput = Types1.AuthPortalsRemoveResponse;
export type PortalsRoutesPutInput = Types1.AuthPortalsRoutesPutRequest;
export type PortalsRoutesPutOutput = Types1.AuthPortalsRoutesPutResponse;
export type PortalsRoutesRemoveInput = Types1.AuthPortalsRoutesRemoveRequest;
export type PortalsRoutesRemoveOutput = Types1.AuthPortalsRoutesRemoveResponse;
export type ServiceInstancesDisableInput = Types1.AuthServiceInstancesDisableRequest;
export type ServiceInstancesDisableOutput = Types1.AuthServiceInstancesDisableResponse;
export type ServiceInstancesEnableInput = Types1.AuthServiceInstancesEnableRequest;
export type ServiceInstancesEnableOutput = Types1.AuthServiceInstancesEnableResponse;
export type ServiceInstancesListInput = Types1.AuthServiceInstancesListRequest;
export type ServiceInstancesListOutput = Types1.AuthServiceInstancesListResponse;
export type ServiceInstancesProvisionInput = Types1.AuthServiceInstancesProvisionRequest;
export type ServiceInstancesProvisionOutput = Types1.AuthServiceInstancesProvisionResponse;
export type ServiceInstancesRemoveInput = Types1.AuthServiceInstancesRemoveRequest;
export type ServiceInstancesRemoveOutput = Types1.AuthServiceInstancesRemoveResponse;
export type SessionsListInput = Types1.AuthSessionsListRequest;
export type SessionsListOutput = Types1.AuthSessionsListResponse;
export type SessionsLogoutInput = Types1.AuthSessionsLogoutRequest;
export type SessionsLogoutOutput = Types1.AuthSessionsLogoutResponse;
export type SessionsMeInput = Types1.AuthSessionsMeRequest;
export type SessionsMeOutput = Types1.AuthSessionsMeResponse;
export type SessionsRevokeInput = Types1.AuthSessionsRevokeRequest;
export type SessionsRevokeOutput = Types1.AuthSessionsRevokeResponse;
export type UserIdentitiesListInput = Types1.AuthUserIdentitiesListRequest;
export type UserIdentitiesListOutput = Types1.AuthUserIdentitiesListResponse;
export type UserIdentitiesUnlinkInput = Types1.AuthUserIdentitiesUnlinkRequest;
export type UserIdentitiesUnlinkOutput = Types1.AuthUserIdentitiesUnlinkResponse;
export type UsersCreateInput = Types1.AuthUsersCreateRequest;
export type UsersCreateOutput = Types1.AuthUsersCreateResponse;
export type UsersGetInput = Types1.AuthUsersGetRequest;
export type UsersGetOutput = Types1.AuthUsersGetResponse;
export type UsersIdentityLinkCreateInput = Types1.AuthUsersIdentityLinkCreateRequest;
export type UsersIdentityLinkCreateOutput = Types1.AuthUsersIdentityLinkCreateResponse;
export type UsersListInput = Types1.AuthUsersListRequest;
export type UsersListOutput = Types1.AuthUsersListResponse;
export type UsersPasswordChangeInput = Types1.AuthUsersPasswordChangeRequest;
export type UsersPasswordChangeOutput = Types1.AuthUsersPasswordChangeResponse;
export type UsersPasswordResetCreateInput = Types1.AuthUsersPasswordResetCreateRequest;
export type UsersPasswordResetCreateOutput = Types1.AuthUsersPasswordResetCreateResponse;
export type UsersResolveInput = Types1.AuthUsersResolveRequest;
export type UsersResolveOutput = Types1.AuthUsersResolveResponse;
export type UsersUpdateInput = Types1.AuthUsersUpdateRequest;
export type UsersUpdateOutput = Types1.AuthUsersUpdateResponse;
export type DeviceUserAuthoritiesResolveInput = Types1.AuthDeviceUserAuthoritiesResolveRequest;
export type DeviceUserAuthoritiesResolveOutput = Types1.AuthDeviceUserAuthoritiesResolveResponse;
export type DeviceUserAuthoritiesResolveProgress = Types1.AuthDeviceUserAuthoritiesResolveProgress;
export type DeviceUserAuthoritiesResolveUpdate = Types1.AuthDeviceUserAuthoritiesResolveProgress;
export type ConnectionsClosedEvent = Types1.AuthConnectionsClosedEvent;
export type ConnectionsKickedEvent = Types1.AuthConnectionsKickedEvent;
export type ConnectionsOpenedEvent = Types1.AuthConnectionsOpenedEvent;
export type DeviceUserAuthoritiesApprovedEvent = Types1.AuthDeviceUserAuthoritiesApprovedEvent;
export type DeviceUserAuthoritiesRequestedEvent = Types1.AuthDeviceUserAuthoritiesRequestedEvent;
export type DeviceUserAuthoritiesResolvedEvent = Types1.AuthDeviceUserAuthoritiesResolvedEvent;
export type DeviceUserAuthoritiesReviewRequestedEvent = Types1.AuthDeviceUserAuthoritiesReviewRequestedEvent;
export type GrantsChangedEvent = Types1.AuthGrantsChangedEvent;
export type IssuersRevokedEvent = Types1.AuthIssuersRevokedEvent;
export type SessionsRevokedEvent = Types1.AuthSessionsRevokedEvent;
declare const __api: {
	readonly identity: "trellis.auth@v1";
	readonly actions: {
		readonly "rpc:Capabilities.List": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Capabilities.List";
			readonly input: typeof Types1.AuthCapabilitiesListRequestCodec;
			readonly output: typeof Types1.AuthCapabilitiesListResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: "cursor";
		};
		readonly "rpc:CapabilityGroups.Delete": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:CapabilityGroups.Delete";
			readonly input: typeof Types1.AuthCapabilityGroupsDeleteRequestCodec;
			readonly output: typeof Types1.AuthCapabilityGroupsDeleteResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:CapabilityGroups.Get": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:CapabilityGroups.Get";
			readonly input: typeof Types1.AuthCapabilityGroupsGetRequestCodec;
			readonly output: typeof Types1.AuthCapabilityGroupsGetResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:CapabilityGroups.List": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:CapabilityGroups.List";
			readonly input: typeof Types1.AuthCapabilityGroupsListRequestCodec;
			readonly output: typeof Types1.AuthCapabilityGroupsListResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: "cursor";
		};
		readonly "rpc:CapabilityGroups.Put": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:CapabilityGroups.Put";
			readonly input: typeof Types1.AuthCapabilityGroupsPutRequestCodec;
			readonly output: typeof Types1.AuthCapabilityGroupsPutResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Connections.Kick": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Connections.Kick";
			readonly input: typeof Types1.AuthConnectionsKickRequestCodec;
			readonly output: typeof Types1.AuthConnectionsKickResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Connections.List": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Connections.List";
			readonly input: typeof Types1.AuthConnectionsListRequestCodec;
			readonly output: typeof Types1.AuthConnectionsListResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: "cursor";
		};
		readonly "rpc:Deployments.Apply": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Deployments.Apply";
			readonly input: typeof Types1.AuthDeploymentsApplyRequestCodec;
			readonly output: typeof Types1.AuthDeploymentsApplyResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Deployments.Create": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Deployments.Create";
			readonly input: typeof Types1.AuthDeploymentsCreateRequestCodec;
			readonly output: typeof Types1.AuthDeploymentsCreateResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Deployments.Disable": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Deployments.Disable";
			readonly input: typeof Types1.AuthDeploymentsDisableRequestCodec;
			readonly output: typeof Types1.AuthDeploymentsDisableResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Deployments.Enable": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Deployments.Enable";
			readonly input: typeof Types1.AuthDeploymentsEnableRequestCodec;
			readonly output: typeof Types1.AuthDeploymentsEnableResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Deployments.Get": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Deployments.Get";
			readonly input: typeof Types1.AuthDeploymentsGetRequestCodec;
			readonly output: typeof Types1.AuthDeploymentsGetResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Deployments.List": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Deployments.List";
			readonly input: typeof Types1.AuthDeploymentsListRequestCodec;
			readonly output: typeof Types1.AuthDeploymentsListResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: "cursor";
		};
		readonly "rpc:Deployments.Remove": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Deployments.Remove";
			readonly input: typeof Types1.AuthDeploymentsRemoveRequestCodec;
			readonly output: typeof Types1.AuthDeploymentsRemoveResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:DeviceUserAuthorities.List": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:DeviceUserAuthorities.List";
			readonly input: typeof Types1.AuthDeviceUserAuthoritiesListRequestCodec;
			readonly output: typeof Types1.AuthDeviceUserAuthoritiesListResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: "cursor";
		};
		readonly "rpc:DeviceUserAuthorities.Reviews.Decide": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:DeviceUserAuthorities.Reviews.Decide";
			readonly input: typeof Types1.AuthDeviceUserAuthoritiesReviewsDecideRequestCodec;
			readonly output: typeof Types1.AuthDeviceUserAuthoritiesReviewsDecideResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:DeviceUserAuthorities.Reviews.List": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:DeviceUserAuthorities.Reviews.List";
			readonly input: typeof Types1.AuthDeviceUserAuthoritiesReviewsListRequestCodec;
			readonly output: typeof Types1.AuthDeviceUserAuthoritiesReviewsListResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: "cursor";
		};
		readonly "rpc:DeviceUserAuthorities.Revoke": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:DeviceUserAuthorities.Revoke";
			readonly input: typeof Types1.AuthDeviceUserAuthoritiesRevokeRequestCodec;
			readonly output: typeof Types1.AuthDeviceUserAuthoritiesRevokeResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Devices.Disable": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Devices.Disable";
			readonly input: typeof Types1.AuthDevicesDisableRequestCodec;
			readonly output: typeof Types1.AuthDevicesDisableResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Devices.Enable": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Devices.Enable";
			readonly input: typeof Types1.AuthDevicesEnableRequestCodec;
			readonly output: typeof Types1.AuthDevicesEnableResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Devices.List": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Devices.List";
			readonly input: typeof Types1.AuthDevicesListRequestCodec;
			readonly output: typeof Types1.AuthDevicesListResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: "cursor";
		};
		readonly "rpc:Devices.Provision": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Devices.Provision";
			readonly input: typeof Types1.AuthDevicesProvisionRequestCodec;
			readonly output: typeof Types1.AuthDevicesProvisionResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Devices.Remove": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Devices.Remove";
			readonly input: typeof Types1.AuthDevicesRemoveRequestCodec;
			readonly output: typeof Types1.AuthDevicesRemoveResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Grants.Get": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Grants.Get";
			readonly input: typeof Types1.AuthGrantsGetRequestCodec;
			readonly output: typeof Types1.AuthGrantsGetResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Grants.List": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Grants.List";
			readonly input: typeof Types1.AuthGrantsListRequestCodec;
			readonly output: typeof Types1.AuthGrantsListResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: "cursor";
		};
		readonly "rpc:Grants.Revoke": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Grants.Revoke";
			readonly input: typeof Types1.AuthGrantsRevokeRequestCodec;
			readonly output: typeof Types1.AuthGrantsMutationResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Grants.Set": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Grants.Set";
			readonly input: typeof Types1.AuthGrantsSetRequestCodec;
			readonly output: typeof Types1.AuthGrantsMutationResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Issuers.Revoke": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Issuers.Revoke";
			readonly input: typeof Types1.AuthIssuersRevokeRequestCodec;
			readonly output: typeof Types1.AuthIssuersRevokeResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Participants.Get": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Participants.Get";
			readonly input: typeof Types1.AuthParticipantsGetRequestCodec;
			readonly output: typeof Types1.AuthParticipantsGetResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Participants.Install": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Participants.Install";
			readonly input: typeof Types1.AuthParticipantsInstallRequestCodec;
			readonly output: typeof Types1.AuthParticipantsInstallResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Participants.List": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Participants.List";
			readonly input: typeof Types1.AuthParticipantsListRequestCodec;
			readonly output: typeof Types1.AuthParticipantsListResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: "cursor";
		};
		readonly "rpc:Portals.Get": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Portals.Get";
			readonly input: typeof Types1.AuthPortalsGetRequestCodec;
			readonly output: typeof Types1.AuthPortalsGetResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Portals.GrantOverrides.List": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Portals.GrantOverrides.List";
			readonly input: typeof Types1.AuthPortalsGrantOverridesListRequestCodec;
			readonly output: typeof Types1.AuthPortalsGrantOverridesListResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: "cursor";
		};
		readonly "rpc:Portals.GrantOverrides.Put": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Portals.GrantOverrides.Put";
			readonly input: typeof Types1.AuthPortalsGrantOverridesPutRequestCodec;
			readonly output: typeof Types1.AuthPortalsGrantOverridesPutResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Portals.GrantOverrides.Remove": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Portals.GrantOverrides.Remove";
			readonly input: typeof Types1.AuthPortalsGrantOverridesRemoveRequestCodec;
			readonly output: typeof Types1.AuthPortalsGrantOverridesRemoveResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Portals.List": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Portals.List";
			readonly input: typeof Types1.AuthPortalsListRequestCodec;
			readonly output: typeof Types1.AuthPortalsListResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: "cursor";
		};
		readonly "rpc:Portals.LoginSettings.Get": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Portals.LoginSettings.Get";
			readonly input: typeof Types1.AuthPortalsLoginSettingsGetRequestCodec;
			readonly output: typeof Types1.AuthPortalsLoginSettingsGetResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Portals.LoginSettings.Update": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Portals.LoginSettings.Update";
			readonly input: typeof Types1.AuthPortalsLoginSettingsUpdateRequestCodec;
			readonly output: typeof Types1.AuthPortalsLoginSettingsUpdateResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Portals.Put": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Portals.Put";
			readonly input: typeof Types1.AuthPortalsPutRequestCodec;
			readonly output: typeof Types1.AuthPortalsPutResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Portals.Remove": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Portals.Remove";
			readonly input: typeof Types1.AuthPortalsRemoveRequestCodec;
			readonly output: typeof Types1.AuthPortalsRemoveResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Portals.Routes.Put": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Portals.Routes.Put";
			readonly input: typeof Types1.AuthPortalsRoutesPutRequestCodec;
			readonly output: typeof Types1.AuthPortalsRoutesPutResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Portals.Routes.Remove": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Portals.Routes.Remove";
			readonly input: typeof Types1.AuthPortalsRoutesRemoveRequestCodec;
			readonly output: typeof Types1.AuthPortalsRoutesRemoveResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:ServiceInstances.Disable": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:ServiceInstances.Disable";
			readonly input: typeof Types1.AuthServiceInstancesDisableRequestCodec;
			readonly output: typeof Types1.AuthServiceInstancesDisableResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:ServiceInstances.Enable": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:ServiceInstances.Enable";
			readonly input: typeof Types1.AuthServiceInstancesEnableRequestCodec;
			readonly output: typeof Types1.AuthServiceInstancesEnableResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:ServiceInstances.List": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:ServiceInstances.List";
			readonly input: typeof Types1.AuthServiceInstancesListRequestCodec;
			readonly output: typeof Types1.AuthServiceInstancesListResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: "cursor";
		};
		readonly "rpc:ServiceInstances.Provision": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:ServiceInstances.Provision";
			readonly input: typeof Types1.AuthServiceInstancesProvisionRequestCodec;
			readonly output: typeof Types1.AuthServiceInstancesProvisionResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:ServiceInstances.Remove": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:ServiceInstances.Remove";
			readonly input: typeof Types1.AuthServiceInstancesRemoveRequestCodec;
			readonly output: typeof Types1.AuthServiceInstancesRemoveResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Sessions.List": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Sessions.List";
			readonly input: typeof Types1.AuthSessionsListRequestCodec;
			readonly output: typeof Types1.AuthSessionsListResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: "cursor";
		};
		readonly "rpc:Sessions.Logout": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Sessions.Logout";
			readonly input: typeof Types1.AuthSessionsLogoutRequestCodec;
			readonly output: typeof Types1.AuthSessionsLogoutResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Sessions.Me": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Sessions.Me";
			readonly input: typeof Types1.AuthSessionsMeRequestCodec;
			readonly output: typeof Types1.AuthSessionsMeResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Sessions.Revoke": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Sessions.Revoke";
			readonly input: typeof Types1.AuthSessionsRevokeRequestCodec;
			readonly output: typeof Types1.AuthSessionsRevokeResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:UserIdentities.List": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:UserIdentities.List";
			readonly input: typeof Types1.AuthUserIdentitiesListRequestCodec;
			readonly output: typeof Types1.AuthUserIdentitiesListResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: "cursor";
		};
		readonly "rpc:UserIdentities.Unlink": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:UserIdentities.Unlink";
			readonly input: typeof Types1.AuthUserIdentitiesUnlinkRequestCodec;
			readonly output: typeof Types1.AuthUserIdentitiesUnlinkResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Users.Create": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Users.Create";
			readonly input: typeof Types1.AuthUsersCreateRequestCodec;
			readonly output: typeof Types1.AuthUsersCreateResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Users.Get": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Users.Get";
			readonly input: typeof Types1.AuthUsersGetRequestCodec;
			readonly output: typeof Types1.AuthUsersGetResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Users.IdentityLink.Create": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Users.IdentityLink.Create";
			readonly input: typeof Types1.AuthUsersIdentityLinkCreateRequestCodec;
			readonly output: typeof Types1.AuthUsersIdentityLinkCreateResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Users.List": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Users.List";
			readonly input: typeof Types1.AuthUsersListRequestCodec;
			readonly output: typeof Types1.AuthUsersListResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: "cursor";
		};
		readonly "rpc:Users.Password.Change": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Users.Password.Change";
			readonly input: typeof Types1.AuthUsersPasswordChangeRequestCodec;
			readonly output: typeof Types1.AuthUsersPasswordChangeResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Users.PasswordReset.Create": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Users.PasswordReset.Create";
			readonly input: typeof Types1.AuthUsersPasswordResetCreateRequestCodec;
			readonly output: typeof Types1.AuthUsersPasswordResetCreateResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Users.Resolve": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Users.Resolve";
			readonly input: typeof Types1.AuthUsersResolveRequestCodec;
			readonly output: typeof Types1.AuthUsersResolveResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "rpc:Users.Update": {
			readonly kind: "rpc";
			readonly descriptorName: "rpc:Users.Update";
			readonly input: typeof Types1.AuthUsersUpdateRequestCodec;
			readonly output: typeof Types1.AuthUsersUpdateResponseCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly download: false;
			readonly pagination: undefined;
		};
		readonly "operation:DeviceUserAuthorities.Resolve": {
			readonly kind: "operation";
			readonly descriptorName: "operation:DeviceUserAuthorities.Resolve";
			readonly input: typeof Types1.AuthDeviceUserAuthoritiesResolveRequestCodec;
			readonly output: typeof Types1.AuthDeviceUserAuthoritiesResolveResponseCodec;
			readonly progress: typeof Types1.AuthDeviceUserAuthoritiesResolveProgressCodec;
			readonly update: typeof Types1.AuthDeviceUserAuthoritiesResolveProgressCodec;
			readonly errors: readonly [typeof AuthError, typeof UnexpectedError, typeof ValidationError];
			readonly signals: {};
			readonly upload: false;
		};
		readonly "event:Connections.Closed": {
			readonly kind: "event";
			readonly descriptorName: "event:Connections.Closed";
			readonly payload: typeof Types1.AuthConnectionsClosedEventCodec;
			readonly parameters: readonly [];
		};
		readonly "event:Connections.Kicked": {
			readonly kind: "event";
			readonly descriptorName: "event:Connections.Kicked";
			readonly payload: typeof Types1.AuthConnectionsKickedEventCodec;
			readonly parameters: readonly [];
		};
		readonly "event:Connections.Opened": {
			readonly kind: "event";
			readonly descriptorName: "event:Connections.Opened";
			readonly payload: typeof Types1.AuthConnectionsOpenedEventCodec;
			readonly parameters: readonly [];
		};
		readonly "event:DeviceUserAuthorities.Approved": {
			readonly kind: "event";
			readonly descriptorName: "event:DeviceUserAuthorities.Approved";
			readonly payload: typeof Types1.AuthDeviceUserAuthoritiesApprovedEventCodec;
			readonly parameters: readonly [readonly ["deploymentId"]];
		};
		readonly "event:DeviceUserAuthorities.Requested": {
			readonly kind: "event";
			readonly descriptorName: "event:DeviceUserAuthorities.Requested";
			readonly payload: typeof Types1.AuthDeviceUserAuthoritiesRequestedEventCodec;
			readonly parameters: readonly [readonly ["deploymentId"]];
		};
		readonly "event:DeviceUserAuthorities.Resolved": {
			readonly kind: "event";
			readonly descriptorName: "event:DeviceUserAuthorities.Resolved";
			readonly payload: typeof Types1.AuthDeviceUserAuthoritiesResolvedEventCodec;
			readonly parameters: readonly [readonly ["deploymentId"]];
		};
		readonly "event:DeviceUserAuthorities.ReviewRequested": {
			readonly kind: "event";
			readonly descriptorName: "event:DeviceUserAuthorities.ReviewRequested";
			readonly payload: typeof Types1.AuthDeviceUserAuthoritiesReviewRequestedEventCodec;
			readonly parameters: readonly [readonly ["deploymentId"]];
		};
		readonly "event:Grants.Changed": {
			readonly kind: "event";
			readonly descriptorName: "event:Grants.Changed";
			readonly payload: typeof Types1.AuthGrantsChangedEventCodec;
			readonly parameters: readonly [];
		};
		readonly "event:Issuers.Revoked": {
			readonly kind: "event";
			readonly descriptorName: "event:Issuers.Revoked";
			readonly payload: typeof Types1.AuthIssuersRevokedEventCodec;
			readonly parameters: readonly [];
		};
		readonly "event:Sessions.Revoked": {
			readonly kind: "event";
			readonly descriptorName: "event:Sessions.Revoked";
			readonly payload: typeof Types1.AuthSessionsRevokedEventCodec;
			readonly parameters: readonly [];
		};
	};
	readonly packageEvidence: unknown;
};
export declare const API: typeof __api;
export declare const API_DIGEST: "gXd9NIBjIa49mInD88kcXFC5_pVuL7cvibchdpdXvKo";
export {};
