[package]
name = "trellis-web-generated"
version = "0.100.0-rc.2"

[sources]
console = "contract.trellis"

[dependencies]
trellis = { package = "trellis", path = "../crates/runtime" }

[generate.typescript]
output = "trellis"
